// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/deployerpb/deployer.proto

package deployerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{0}
}

type CreateBackupResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Path      string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // full path of the written file
	Bytes     int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	CreatedAt string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	// Verified reports that the pg_restore -l check passed. When false, note
	// carries the reason: the file was still written, but do not trust it
	// blindly.
	Verified      bool   `protobuf:"varint,4,opt,name=verified,proto3" json:"verified,omitempty"`
	Note          string `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBackupResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateBackupResponse) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *CreateBackupResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CreateBackupResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *CreateBackupResponse) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type BackupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bytes         int64                  `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupInfo) Reset() {
	*x = BackupInfo{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupInfo) ProtoMessage() {}

func (x *BackupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupInfo.ProtoReflect.Descriptor instead.
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{2}
}

func (x *BackupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackupInfo) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *BackupInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListBackupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsRequest) Reset() {
	*x = ListBackupsRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsRequest) ProtoMessage() {}

func (x *ListBackupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsRequest.ProtoReflect.Descriptor instead.
func (*ListBackupsRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{3}
}

type ListBackupsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Backups []*BackupInfo          `protobuf:"bytes,1,rep,name=backups,proto3" json:"backups,omitempty"`
	// KeepLimit says how many backups are retained. The UI shows it so that
	// the disappearance of older files is never a mystery.
	KeepLimit     int32 `protobuf:"varint,2,opt,name=keep_limit,json=keepLimit,proto3" json:"keep_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackupsResponse) Reset() {
	*x = ListBackupsResponse{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackupsResponse) ProtoMessage() {}

func (x *ListBackupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackupsResponse.ProtoReflect.Descriptor instead.
func (*ListBackupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{4}
}

func (x *ListBackupsResponse) GetBackups() []*BackupInfo {
	if x != nil {
		return x.Backups
	}
	return nil
}

func (x *ListBackupsResponse) GetKeepLimit() int32 {
	if x != nil {
		return x.KeepLimit
	}
	return 0
}

type ListContainersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// managed_only=true restricts the result to containers labelled
// muvon.managed=true.
	ManagedOnly bool   `protobuf:"varint,1,opt,name=managed_only,json=managedOnly,proto3" json:"managed_only,omitempty"`
	Project     string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Component   string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	// state is one of "", "running" or "exited"; empty means both.
	State         string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{5}
}

func (x *ListContainersRequest) GetManagedOnly() bool {
	if x != nil {
		return x.ManagedOnly
	}
	return false
}

func (x *ListContainersRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListContainersRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ListContainersRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerDetail     `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{6}
}

func (x *ListContainersResponse) GetContainers() []*ContainerDetail {
	if x != nil {
		return x.Containers
	}
	return nil
}

type GetContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // full ID veya prefix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerRequest) Reset() {
	*x = GetContainerRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerRequest) ProtoMessage() {}

func (x *GetContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerRequest.ProtoReflect.Descriptor instead.
func (*GetContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{7}
}

func (x *GetContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ContainerDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// state is one of Docker's canonical values: created, running, paused,
	// restarting, removing, exited, dead.
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// status — Docker UI'inin gosterdigi insan-okunabilir cumle, ornek:
	// "Up 5 minutes (healthy)".
	Status string            `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// RFC3339; when the container started (State.StartedAt while Up).
	StartedAt string `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// RFC3339; State.FinishedAt if it exited, empty for a running container.
	FinishedAt string `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode   int32  `protobuf:"varint,10,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Label-derived fields pulled out of Inspect, so the admin UI can fill its
	// search fields without parsing labels itself.
	Project       string `protobuf:"bytes,11,opt,name=project,proto3" json:"project,omitempty"`                      // muvon.project
	Component     string `protobuf:"bytes,12,opt,name=component,proto3" json:"component,omitempty"`                  // muvon.component
	ReleaseId     string `protobuf:"bytes,13,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"` // muvon.release_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerDetail) Reset() {
	*x = ContainerDetail{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDetail) ProtoMessage() {}

func (x *ContainerDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDetail.ProtoReflect.Descriptor instead.
func (*ContainerDetail) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerDetail) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerDetail) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerDetail) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerDetail) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ContainerDetail) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerDetail) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerDetail) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ContainerDetail) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *ContainerDetail) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerDetail) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ContainerDetail) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ContainerDetail) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

type StreamContainerLogsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// tail is how many trailing lines to send on connect; 0 means new lines
	// only; a negative value means the whole existing log, which is expensive
	// to start with and should not be used.
	Tail int32 `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"`
	// follow=true bagli kalir ve container son bulana kadar yeni satirlari
	// surekli gonderir.
	Follow bool `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	// streams: bos = "stdout,stderr"; yoksa istenenleri filtrele. Docker
	// API tarafindaki ayar; sunucu varsayilani stdout+stderr.
	Streams []string `protobuf:"bytes,4,rep,name=streams,proto3" json:"streams,omitempty"`
	// since is RFC3339: send only lines after that time. Empty falls back to
	// docker logs' own default behaviour.
	Since         string `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContainerLogsRequest) Reset() {
	*x = StreamContainerLogsRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerLogsRequest) ProtoMessage() {}

func (x *StreamContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{9}
}

func (x *StreamContainerLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StreamContainerLogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *StreamContainerLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *StreamContainerLogsRequest) GetStreams() []string {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *StreamContainerLogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

type ContainerLogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp is the RFC3339Nano value the Docker daemon supplies.
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// stream is "stdout" or "stderr", taken from the multiplexed stream header.
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// line is a single log line with its newline stripped.
	Line string `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	// truncated=true: kaynak satir max_line'i astigi icin server tarafindan
	// split it. The UI may join such lines with an ellipsis.
	Truncated bool `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	// seq is a monotonic counter inside the server's tail goroutine, used to
	// order two lines that share the same microsecond.
	Seq int64 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	// synthetic=true means muvon produced the line itself (for example
	// "dropped N lines"). The UI may render those differently.
	Synthetic     bool `protobuf:"varint,6,opt,name=synthetic,proto3" json:"synthetic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLogChunk) Reset() {
	*x = ContainerLogChunk{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogChunk) ProtoMessage() {}

func (x *ContainerLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogChunk.ProtoReflect.Descriptor instead.
func (*ContainerLogChunk) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerLogChunk) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ContainerLogChunk) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ContainerLogChunk) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *ContainerLogChunk) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ContainerLogChunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ContainerLogChunk) GetSynthetic() bool {
	if x != nil {
		return x.Synthetic
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{11}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok=true means the deployer and its Docker daemon access are working.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// last_tick_age_seconds is how long ago the deployer's last tick ran.
	// 0 means unknown.
	LastTickAgeSeconds int64 `protobuf:"varint,2,opt,name=last_tick_age_seconds,json=lastTickAgeSeconds,proto3" json:"last_tick_age_seconds,omitempty"`
	// active_tail_streams is how many StreamContainerLogs calls are live.
	ActiveTailStreams int32 `protobuf:"varint,3,opt,name=active_tail_streams,json=activeTailStreams,proto3" json:"active_tail_streams,omitempty"`
	// shipper_active = logship aktif container sayisi (persistans icin
	// tail edilenler).
	ShipperActiveContainers int32 `protobuf:"varint,4,opt,name=shipper_active_containers,json=shipperActiveContainers,proto3" json:"shipper_active_containers,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{12}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetLastTickAgeSeconds() int64 {
	if x != nil {
		return x.LastTickAgeSeconds
	}
	return 0
}

func (x *HealthResponse) GetActiveTailStreams() int32 {
	if x != nil {
		return x.ActiveTailStreams
	}
	return 0
}

func (x *HealthResponse) GetShipperActiveContainers() int32 {
	if x != nil {
		return x.ShipperActiveContainers
	}
	return 0
}

type SelfImageDigestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfImageDigestRequest) Reset() {
	*x = SelfImageDigestRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImageDigestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImageDigestRequest) ProtoMessage() {}

func (x *SelfImageDigestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImageDigestRequest.ProtoReflect.Descriptor instead.
func (*SelfImageDigestRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{13}
}

type SelfImageDigestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The image digest each service's container is running.
	// A missing service means unknown: no container, or Docker errored.
	Digests       map[string]string `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfImageDigestResponse) Reset() {
	*x = SelfImageDigestResponse{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfImageDigestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfImageDigestResponse) ProtoMessage() {}

func (x *SelfImageDigestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfImageDigestResponse.ProtoReflect.Descriptor instead.
func (*SelfImageDigestResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{14}
}

func (x *SelfImageDigestResponse) GetDigests() map[string]string {
	if x != nil {
		return x.Digests
	}
	return nil
}

type SystemUpgradeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// target_tag is ":latest" (the default), ":v0.1.0" and so on. It is
	// written to the VERSION variable in compose's .env and the pull follows
	// that tag.
	TargetTag string `protobuf:"bytes,1,opt,name=target_tag,json=targetTag,proto3" json:"target_tag,omitempty"`
	// take_backup=true takes a pg_dump before the pull.
	TakeBackup    bool `protobuf:"varint,2,opt,name=take_backup,json=takeBackup,proto3" json:"take_backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemUpgradeRequest) Reset() {
	*x = SystemUpgradeRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemUpgradeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemUpgradeRequest) ProtoMessage() {}

func (x *SystemUpgradeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemUpgradeRequest.ProtoReflect.Descriptor instead.
func (*SystemUpgradeRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{15}
}

func (x *SystemUpgradeRequest) GetTargetTag() string {
	if x != nil {
		return x.TargetTag
	}
	return ""
}

func (x *SystemUpgradeRequest) GetTakeBackup() bool {
	if x != nil {
		return x.TakeBackup
	}
	return false
}

type UpgradeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// step ∈ {locked, pre_check, backup, pull, restart, post_check, done, failed}
	Step string `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	// level ∈ {info, warn, error}
	Level string `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	// A human-readable message, either captured from stdout or written here.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// RFC3339; set by the backend.
	Timestamp string `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// done=true marks the final event. The stream closes after it.
	Done          bool `protobuf:"varint,5,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeEvent) Reset() {
	*x = UpgradeEvent{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEvent) ProtoMessage() {}

func (x *UpgradeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEvent.ProtoReflect.Descriptor instead.
func (*UpgradeEvent) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{16}
}

func (x *UpgradeEvent) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *UpgradeEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *UpgradeEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpgradeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *UpgradeEvent) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_proto_deployerpb_deployer_proto protoreflect.FileDescriptor

const file_proto_deployerpb_deployer_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/deployerpb/deployer.proto\x12\n" +
	"deployerpb\"\x15\n" +
	"\x13CreateBackupRequest\"\x8f\x01\n" +
	"\x14CreateBackupResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\bverified\x18\x04 \x01(\bR\bverified\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"U\n" +
	"\n" +
	"BackupInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x03R\x05bytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x14\n" +
	"\x12ListBackupsRequest\"f\n" +
	"\x13ListBackupsResponse\x120\n" +
	"\abackups\x18\x01 \x03(\v2\x16.deployerpb.BackupInfoR\abackups\x12\x1d\n" +
	"\n" +
	"keep_limit\x18\x02 \x01(\x05R\tkeepLimit\"\x88\x01\n" +
	"\x15ListContainersRequest\x12!\n" +
	"\fmanaged_only\x18\x01 \x01(\bR\vmanagedOnly\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"U\n" +
	"\x16ListContainersResponse\x12;\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1b.deployerpb.ContainerDetailR\n" +
	"containers\"8\n" +
	"\x13GetContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\xf2\x03\n" +
	"\x0fContainerDetail\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12?\n" +
	"\x06labels\x18\a \x03(\v2'.deployerpb.ContainerDetail.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\t \x01(\tR\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\n" +
	" \x01(\x05R\bexitCode\x12\x18\n" +
	"\aproject\x18\v \x01(\tR\aproject\x12\x1c\n" +
	"\tcomponent\x18\f \x01(\tR\tcomponent\x12\x1d\n" +
	"\n" +
	"release_id\x18\r \x01(\tR\treleaseId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x1aStreamContainerLogsRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\x05R\x04tail\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x18\n" +
	"\astreams\x18\x04 \x03(\tR\astreams\x12\x14\n" +
	"\x05since\x18\x05 \x01(\tR\x05since\"\xab\x01\n" +
	"\x11ContainerLogChunk\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\x1c\n" +
	"\tsynthetic\x18\x06 \x01(\bR\tsynthetic\"\x0f\n" +
	"\rHealthRequest\"\xbf\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\x15last_tick_age_seconds\x18\x02 \x01(\x03R\x12lastTickAgeSeconds\x12.\n" +
	"\x13active_tail_streams\x18\x03 \x01(\x05R\x11activeTailStreams\x12:\n" +
	"\x19shipper_active_containers\x18\x04 \x01(\x05R\x17shipperActiveContainers\"\x18\n" +
	"\x16SelfImageDigestRequest\"\xa1\x01\n" +
	"\x17SelfImageDigestResponse\x12J\n" +
	"\adigests\x18\x01 \x03(\v20.deployerpb.SelfImageDigestResponse.DigestsEntryR\adigests\x1a:\n" +
	"\fDigestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\x14SystemUpgradeRequest\x12\x1d\n" +
	"\n" +
	"target_tag\x18\x01 \x01(\tR\ttargetTag\x12\x1f\n" +
	"\vtake_backup\x18\x02 \x01(\bR\n" +
	"takeBackup\"\x84\x01\n" +
	"\fUpgradeEvent\x12\x12\n" +
	"\x04step\x18\x01 \x01(\tR\x04step\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04done\x18\x05 \x01(\bR\x04done2\xa7\x05\n" +
	"\x0fDeployerService\x12W\n" +
	"\x0eListContainers\x12!.deployerpb.ListContainersRequest\x1a\".deployerpb.ListContainersResponse\x12L\n" +
	"\fGetContainer\x12\x1f.deployerpb.GetContainerRequest\x1a\x1b.deployerpb.ContainerDetail\x12^\n" +
	"\x13StreamContainerLogs\x12&.deployerpb.StreamContainerLogsRequest\x1a\x1d.deployerpb.ContainerLogChunk0\x01\x12?\n" +
	"\x06Health\x12\x19.deployerpb.HealthRequest\x1a\x1a.deployerpb.HealthResponse\x12Z\n" +
	"\x0fSelfImageDigest\x12\".deployerpb.SelfImageDigestRequest\x1a#.deployerpb.SelfImageDigestResponse\x12M\n" +
	"\rSystemUpgrade\x12 .deployerpb.SystemUpgradeRequest\x1a\x18.deployerpb.UpgradeEvent0\x01\x12Q\n" +
	"\fCreateBackup\x12\x1f.deployerpb.CreateBackupRequest\x1a .deployerpb.CreateBackupResponse\x12N\n" +
	"\vListBackups\x12\x1e.deployerpb.ListBackupsRequest\x1a\x1f.deployerpb.ListBackupsResponseB\x18Z\x16muvon/proto/deployerpbb\x06proto3"

var (
	file_proto_deployerpb_deployer_proto_rawDescOnce sync.Once
	file_proto_deployerpb_deployer_proto_rawDescData []byte
)

func file_proto_deployerpb_deployer_proto_rawDescGZIP() []byte {
	file_proto_deployerpb_deployer_proto_rawDescOnce.Do(func() {
		file_proto_deployerpb_deployer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deployerpb_deployer_proto_rawDesc), len(file_proto_deployerpb_deployer_proto_rawDesc)))
	})
	return file_proto_deployerpb_deployer_proto_rawDescData
}

var file_proto_deployerpb_deployer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_deployerpb_deployer_proto_goTypes = []any{
	(*CreateBackupRequest)(nil),        // 0: deployerpb.CreateBackupRequest
	(*CreateBackupResponse)(nil),       // 1: deployerpb.CreateBackupResponse
	(*BackupInfo)(nil),                 // 2: deployerpb.BackupInfo
	(*ListBackupsRequest)(nil),         // 3: deployerpb.ListBackupsRequest
	(*ListBackupsResponse)(nil),        // 4: deployerpb.ListBackupsResponse
	(*ListContainersRequest)(nil),      // 5: deployerpb.ListContainersRequest
	(*ListContainersResponse)(nil),     // 6: deployerpb.ListContainersResponse
	(*GetContainerRequest)(nil),        // 7: deployerpb.GetContainerRequest
	(*ContainerDetail)(nil),            // 8: deployerpb.ContainerDetail
	(*StreamContainerLogsRequest)(nil), // 9: deployerpb.StreamContainerLogsRequest
	(*ContainerLogChunk)(nil),          // 10: deployerpb.ContainerLogChunk
	(*HealthRequest)(nil),              // 11: deployerpb.HealthRequest
	(*HealthResponse)(nil),             // 12: deployerpb.HealthResponse
	(*SelfImageDigestRequest)(nil),     // 13: deployerpb.SelfImageDigestRequest
	(*SelfImageDigestResponse)(nil),    // 14: deployerpb.SelfImageDigestResponse
	(*SystemUpgradeRequest)(nil),       // 15: deployerpb.SystemUpgradeRequest
	(*UpgradeEvent)(nil),               // 16: deployerpb.UpgradeEvent
	nil,                                // 17: deployerpb.ContainerDetail.LabelsEntry
	nil,                                // 18: deployerpb.SelfImageDigestResponse.DigestsEntry
}
var file_proto_deployerpb_deployer_proto_depIdxs = []int32{
	2,  // 0: deployerpb.ListBackupsResponse.backups:type_name -> deployerpb.BackupInfo
	8,  // 1: deployerpb.ListContainersResponse.containers:type_name -> deployerpb.ContainerDetail
	17, // 2: deployerpb.ContainerDetail.labels:type_name -> deployerpb.ContainerDetail.LabelsEntry
	18, // 3: deployerpb.SelfImageDigestResponse.digests:type_name -> deployerpb.SelfImageDigestResponse.DigestsEntry
	5,  // 4: deployerpb.DeployerService.ListContainers:input_type -> deployerpb.ListContainersRequest
	7,  // 5: deployerpb.DeployerService.GetContainer:input_type -> deployerpb.GetContainerRequest
	9,  // 6: deployerpb.DeployerService.StreamContainerLogs:input_type -> deployerpb.StreamContainerLogsRequest
	11, // 7: deployerpb.DeployerService.Health:input_type -> deployerpb.HealthRequest
	13, // 8: deployerpb.DeployerService.SelfImageDigest:input_type -> deployerpb.SelfImageDigestRequest
	15, // 9: deployerpb.DeployerService.SystemUpgrade:input_type -> deployerpb.SystemUpgradeRequest
	0,  // 10: deployerpb.DeployerService.CreateBackup:input_type -> deployerpb.CreateBackupRequest
	3,  // 11: deployerpb.DeployerService.ListBackups:input_type -> deployerpb.ListBackupsRequest
	6,  // 12: deployerpb.DeployerService.ListContainers:output_type -> deployerpb.ListContainersResponse
	8,  // 13: deployerpb.DeployerService.GetContainer:output_type -> deployerpb.ContainerDetail
	10, // 14: deployerpb.DeployerService.StreamContainerLogs:output_type -> deployerpb.ContainerLogChunk
	12, // 15: deployerpb.DeployerService.Health:output_type -> deployerpb.HealthResponse
	14, // 16: deployerpb.DeployerService.SelfImageDigest:output_type -> deployerpb.SelfImageDigestResponse
	16, // 17: deployerpb.DeployerService.SystemUpgrade:output_type -> deployerpb.UpgradeEvent
	1,  // 18: deployerpb.DeployerService.CreateBackup:output_type -> deployerpb.CreateBackupResponse
	4,  // 19: deployerpb.DeployerService.ListBackups:output_type -> deployerpb.ListBackupsResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_deployerpb_deployer_proto_init() }
func file_proto_deployerpb_deployer_proto_init() {
	if File_proto_deployerpb_deployer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deployerpb_deployer_proto_rawDesc), len(file_proto_deployerpb_deployer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deployerpb_deployer_proto_goTypes,
		DependencyIndexes: file_proto_deployerpb_deployer_proto_depIdxs,
		MessageInfos:      file_proto_deployerpb_deployer_proto_msgTypes,
	}.Build()
	File_proto_deployerpb_deployer_proto = out.File
	file_proto_deployerpb_deployer_proto_goTypes = nil
	file_proto_deployerpb_deployer_proto_depIdxs = nil
}
