// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/deployerpb/deployer.proto

package deployerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListContainersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// managed_only=true sadece muvon.managed=true label'li container'lar.
	ManagedOnly bool   `protobuf:"varint,1,opt,name=managed_only,json=managedOnly,proto3" json:"managed_only,omitempty"`
	Project     string `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Component   string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	// state ∈ {"", "running", "exited"}; bos = her ikisi.
	State         string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersRequest) Reset() {
	*x = ListContainersRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersRequest) ProtoMessage() {}

func (x *ListContainersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersRequest.ProtoReflect.Descriptor instead.
func (*ListContainersRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{0}
}

func (x *ListContainersRequest) GetManagedOnly() bool {
	if x != nil {
		return x.ManagedOnly
	}
	return false
}

func (x *ListContainersRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ListContainersRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ListContainersRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListContainersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerDetail     `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContainersResponse) Reset() {
	*x = ListContainersResponse{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContainersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContainersResponse) ProtoMessage() {}

func (x *ListContainersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContainersResponse.ProtoReflect.Descriptor instead.
func (*ListContainersResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{1}
}

func (x *ListContainersResponse) GetContainers() []*ContainerDetail {
	if x != nil {
		return x.Containers
	}
	return nil
}

type GetContainerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"` // full ID veya prefix
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerRequest) Reset() {
	*x = GetContainerRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerRequest) ProtoMessage() {}

func (x *GetContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerRequest.ProtoReflect.Descriptor instead.
func (*GetContainerRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{2}
}

func (x *GetContainerRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type ContainerDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,4,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// state ∈ Docker'in dondurdugu kanonik degerler: created, running,
	// paused, restarting, removing, exited, dead.
	State string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	// status — Docker UI'inin gosterdigi insan-okunabilir cumle, ornek:
	// "Up 5 minutes (healthy)".
	Status string            `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// RFC3339; container start anı (Up için State.StartedAt).
	StartedAt string `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// RFC3339; çıkış varsa State.FinishedAt; aktif container'larda boş.
	FinishedAt string `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	ExitCode   int32  `protobuf:"varint,10,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Inspect'ten cıkarılan label-derived bilgiler — admin UI'in arama
	// alanlarinı doldurmasını kolaylaştırır.
	Project       string `protobuf:"bytes,11,opt,name=project,proto3" json:"project,omitempty"`                      // muvon.project
	Component     string `protobuf:"bytes,12,opt,name=component,proto3" json:"component,omitempty"`                  // muvon.component
	ReleaseId     string `protobuf:"bytes,13,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"` // muvon.release_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerDetail) Reset() {
	*x = ContainerDetail{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDetail) ProtoMessage() {}

func (x *ContainerDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDetail.ProtoReflect.Descriptor instead.
func (*ContainerDetail) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerDetail) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ContainerDetail) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ContainerDetail) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerDetail) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ContainerDetail) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerDetail) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ContainerDetail) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *ContainerDetail) GetFinishedAt() string {
	if x != nil {
		return x.FinishedAt
	}
	return ""
}

func (x *ContainerDetail) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ContainerDetail) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *ContainerDetail) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *ContainerDetail) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

type StreamContainerLogsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContainerId string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// tail = ilk bagli sirasinda gonderilecek son N satir; 0 = sadece yeni
	// satirlar; <0 = tum mevcut log (baslangıc icin maliyetli, kullanmayin).
	Tail int32 `protobuf:"varint,2,opt,name=tail,proto3" json:"tail,omitempty"`
	// follow=true bagli kalir ve container son bulana kadar yeni satirlari
	// surekli gonderir.
	Follow bool `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	// streams: bos = "stdout,stderr"; yoksa istenenleri filtrele. Docker
	// API tarafindaki ayar; sunucu varsayilani stdout+stderr.
	Streams []string `protobuf:"bytes,4,rep,name=streams,proto3" json:"streams,omitempty"`
	// since RFC3339 — sadece bu zamandan sonraki satirlari gonder. Boş
	// ise Docker'in docker logs default davranisi.
	Since         string `protobuf:"bytes,5,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContainerLogsRequest) Reset() {
	*x = StreamContainerLogsRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerLogsRequest) ProtoMessage() {}

func (x *StreamContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{4}
}

func (x *StreamContainerLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StreamContainerLogsRequest) GetTail() int32 {
	if x != nil {
		return x.Tail
	}
	return 0
}

func (x *StreamContainerLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *StreamContainerLogsRequest) GetStreams() []string {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *StreamContainerLogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

type ContainerLogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp Docker daemon'in sagladigi RFC3339Nano.
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// stream ∈ {"stdout","stderr"} — multiplexed stream header'dan cıkarılır.
	Stream string `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	// line — newline-strip edilmis tek bir log satiri.
	Line string `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	// truncated=true: kaynak satir max_line'i astigi icin server tarafindan
	// bolundu. UI bu satiri "..." ile birlestirebilir.
	Truncated bool `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	// seq — server'in tail goroutine'i icinde monoton artan sayac. Iki
	// satir ayni microsaniyeyi paylasirsa siralama icin kullanilir.
	Seq int64 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	// synthetic=true: bu satir muvon tarafından üretilmiştir (örn. "dropped
	// N lines"). UI bunları farklı renderleyebilir.
	Synthetic     bool `protobuf:"varint,6,opt,name=synthetic,proto3" json:"synthetic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLogChunk) Reset() {
	*x = ContainerLogChunk{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogChunk) ProtoMessage() {}

func (x *ContainerLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogChunk.ProtoReflect.Descriptor instead.
func (*ContainerLogChunk) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerLogChunk) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ContainerLogChunk) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ContainerLogChunk) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *ContainerLogChunk) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *ContainerLogChunk) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ContainerLogChunk) GetSynthetic() bool {
	if x != nil {
		return x.Synthetic
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ok = true ise deployer + Docker daemon erisimi calisiyor.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// last_tick_age_seconds = deployer'in son tick'inden bu yana gecen sure.
	// 0 = ulasilamiyor.
	LastTickAgeSeconds int64 `protobuf:"varint,2,opt,name=last_tick_age_seconds,json=lastTickAgeSeconds,proto3" json:"last_tick_age_seconds,omitempty"`
	// active_tail_streams = o anda canli olan StreamContainerLogs sayisi.
	ActiveTailStreams int32 `protobuf:"varint,3,opt,name=active_tail_streams,json=activeTailStreams,proto3" json:"active_tail_streams,omitempty"`
	// shipper_active = logship aktif container sayisi (persistans icin
	// tail edilenler).
	ShipperActiveContainers int32 `protobuf:"varint,4,opt,name=shipper_active_containers,json=shipperActiveContainers,proto3" json:"shipper_active_containers,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_deployerpb_deployer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_deployerpb_deployer_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetLastTickAgeSeconds() int64 {
	if x != nil {
		return x.LastTickAgeSeconds
	}
	return 0
}

func (x *HealthResponse) GetActiveTailStreams() int32 {
	if x != nil {
		return x.ActiveTailStreams
	}
	return 0
}

func (x *HealthResponse) GetShipperActiveContainers() int32 {
	if x != nil {
		return x.ShipperActiveContainers
	}
	return 0
}

var File_proto_deployerpb_deployer_proto protoreflect.FileDescriptor

const file_proto_deployerpb_deployer_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/deployerpb/deployer.proto\x12\n" +
	"deployerpb\"\x88\x01\n" +
	"\x15ListContainersRequest\x12!\n" +
	"\fmanaged_only\x18\x01 \x01(\bR\vmanagedOnly\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"U\n" +
	"\x16ListContainersResponse\x12;\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x1b.deployerpb.ContainerDetailR\n" +
	"containers\"8\n" +
	"\x13GetContainerRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"\xf2\x03\n" +
	"\x0fContainerDetail\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x04 \x01(\tR\vimageDigest\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12?\n" +
	"\x06labels\x18\a \x03(\v2'.deployerpb.ContainerDetail.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\t \x01(\tR\n" +
	"finishedAt\x12\x1b\n" +
	"\texit_code\x18\n" +
	" \x01(\x05R\bexitCode\x12\x18\n" +
	"\aproject\x18\v \x01(\tR\aproject\x12\x1c\n" +
	"\tcomponent\x18\f \x01(\tR\tcomponent\x12\x1d\n" +
	"\n" +
	"release_id\x18\r \x01(\tR\treleaseId\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x1aStreamContainerLogsRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\x05R\x04tail\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12\x18\n" +
	"\astreams\x18\x04 \x03(\tR\astreams\x12\x14\n" +
	"\x05since\x18\x05 \x01(\tR\x05since\"\xab\x01\n" +
	"\x11ContainerLogChunk\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x03R\x03seq\x12\x1c\n" +
	"\tsynthetic\x18\x06 \x01(\bR\tsynthetic\"\x0f\n" +
	"\rHealthRequest\"\xbf\x01\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x121\n" +
	"\x15last_tick_age_seconds\x18\x02 \x01(\x03R\x12lastTickAgeSeconds\x12.\n" +
	"\x13active_tail_streams\x18\x03 \x01(\x05R\x11activeTailStreams\x12:\n" +
	"\x19shipper_active_containers\x18\x04 \x01(\x05R\x17shipperActiveContainers2\xd9\x02\n" +
	"\x0fDeployerService\x12W\n" +
	"\x0eListContainers\x12!.deployerpb.ListContainersRequest\x1a\".deployerpb.ListContainersResponse\x12L\n" +
	"\fGetContainer\x12\x1f.deployerpb.GetContainerRequest\x1a\x1b.deployerpb.ContainerDetail\x12^\n" +
	"\x13StreamContainerLogs\x12&.deployerpb.StreamContainerLogsRequest\x1a\x1d.deployerpb.ContainerLogChunk0\x01\x12?\n" +
	"\x06Health\x12\x19.deployerpb.HealthRequest\x1a\x1a.deployerpb.HealthResponseB\x18Z\x16muvon/proto/deployerpbb\x06proto3"

var (
	file_proto_deployerpb_deployer_proto_rawDescOnce sync.Once
	file_proto_deployerpb_deployer_proto_rawDescData []byte
)

func file_proto_deployerpb_deployer_proto_rawDescGZIP() []byte {
	file_proto_deployerpb_deployer_proto_rawDescOnce.Do(func() {
		file_proto_deployerpb_deployer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_deployerpb_deployer_proto_rawDesc), len(file_proto_deployerpb_deployer_proto_rawDesc)))
	})
	return file_proto_deployerpb_deployer_proto_rawDescData
}

var file_proto_deployerpb_deployer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_deployerpb_deployer_proto_goTypes = []any{
	(*ListContainersRequest)(nil),      // 0: deployerpb.ListContainersRequest
	(*ListContainersResponse)(nil),     // 1: deployerpb.ListContainersResponse
	(*GetContainerRequest)(nil),        // 2: deployerpb.GetContainerRequest
	(*ContainerDetail)(nil),            // 3: deployerpb.ContainerDetail
	(*StreamContainerLogsRequest)(nil), // 4: deployerpb.StreamContainerLogsRequest
	(*ContainerLogChunk)(nil),          // 5: deployerpb.ContainerLogChunk
	(*HealthRequest)(nil),              // 6: deployerpb.HealthRequest
	(*HealthResponse)(nil),             // 7: deployerpb.HealthResponse
	nil,                                // 8: deployerpb.ContainerDetail.LabelsEntry
}
var file_proto_deployerpb_deployer_proto_depIdxs = []int32{
	3, // 0: deployerpb.ListContainersResponse.containers:type_name -> deployerpb.ContainerDetail
	8, // 1: deployerpb.ContainerDetail.labels:type_name -> deployerpb.ContainerDetail.LabelsEntry
	0, // 2: deployerpb.DeployerService.ListContainers:input_type -> deployerpb.ListContainersRequest
	2, // 3: deployerpb.DeployerService.GetContainer:input_type -> deployerpb.GetContainerRequest
	4, // 4: deployerpb.DeployerService.StreamContainerLogs:input_type -> deployerpb.StreamContainerLogsRequest
	6, // 5: deployerpb.DeployerService.Health:input_type -> deployerpb.HealthRequest
	1, // 6: deployerpb.DeployerService.ListContainers:output_type -> deployerpb.ListContainersResponse
	3, // 7: deployerpb.DeployerService.GetContainer:output_type -> deployerpb.ContainerDetail
	5, // 8: deployerpb.DeployerService.StreamContainerLogs:output_type -> deployerpb.ContainerLogChunk
	7, // 9: deployerpb.DeployerService.Health:output_type -> deployerpb.HealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_deployerpb_deployer_proto_init() }
func file_proto_deployerpb_deployer_proto_init() {
	if File_proto_deployerpb_deployer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_deployerpb_deployer_proto_rawDesc), len(file_proto_deployerpb_deployer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_deployerpb_deployer_proto_goTypes,
		DependencyIndexes: file_proto_deployerpb_deployer_proto_depIdxs,
		MessageInfos:      file_proto_deployerpb_deployer_proto_msgTypes,
	}.Build()
	File_proto_deployerpb_deployer_proto = out.File
	file_proto_deployerpb_deployer_proto_goTypes = nil
	file_proto_deployerpb_deployer_proto_depIdxs = nil
}
