// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/deployerpb/deployer.proto

package deployerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeployerService_ListContainers_FullMethodName      = "/deployerpb.DeployerService/ListContainers"
	DeployerService_GetContainer_FullMethodName        = "/deployerpb.DeployerService/GetContainer"
	DeployerService_StreamContainerLogs_FullMethodName = "/deployerpb.DeployerService/StreamContainerLogs"
	DeployerService_Health_FullMethodName              = "/deployerpb.DeployerService/Health"
)

// DeployerServiceClient is the client API for DeployerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeployerService — muvon-deployer'in container introspection ve canli
// log akisi sunan gRPC API'si. Sadece muvon admin'in dialerli oldugu
// /run/muvon/deployer.sock Unix soketi uzerinden konusur. Docker socket
// erisimi yalnizca muvon-deployer'da kalir; admin bu RPC ile sinirli bir
// yuzeyden gecer.
type DeployerServiceClient interface {
	// ListContainers active + son acılmış container'ları gosterir. Filtreler
	// ister managed-only ister tum container'lar icin uygulanir. Admin UI'in
	// "Live tail" picker'i bunu cagirir.
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	// GetContainer tek bir container icin durum + label snapshot'ini doner.
	GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*ContainerDetail, error)
	// StreamContainerLogs Docker daemon'a `?follow=1&timestamps=1` ile baglanir,
	// multiplexed stream'i demuks edip her satiri ayri bir mesaj olarak yollar.
	// Yavas tuketici icin sunucu drop-oldest backpressure uygular ve sentetik
	// bir "[muvon] dropped N lines" satiri ile kayip bilgisini akıtır.
	StreamContainerLogs(ctx context.Context, in *StreamContainerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContainerLogChunk], error)
	// Health basit bir liveness probe; admin UI deployer down banner'ini
	// bunun başarısızlığına bağlar.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type deployerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeployerServiceClient(cc grpc.ClientConnInterface) DeployerServiceClient {
	return &deployerServiceClient{cc}
}

func (c *deployerServiceClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, DeployerService_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) GetContainer(ctx context.Context, in *GetContainerRequest, opts ...grpc.CallOption) (*ContainerDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainerDetail)
	err := c.cc.Invoke(ctx, DeployerService_GetContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deployerServiceClient) StreamContainerLogs(ctx context.Context, in *StreamContainerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ContainerLogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeployerService_ServiceDesc.Streams[0], DeployerService_StreamContainerLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamContainerLogsRequest, ContainerLogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployerService_StreamContainerLogsClient = grpc.ServerStreamingClient[ContainerLogChunk]

func (c *deployerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, DeployerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeployerServiceServer is the server API for DeployerService service.
// All implementations must embed UnimplementedDeployerServiceServer
// for forward compatibility.
//
// DeployerService — muvon-deployer'in container introspection ve canli
// log akisi sunan gRPC API'si. Sadece muvon admin'in dialerli oldugu
// /run/muvon/deployer.sock Unix soketi uzerinden konusur. Docker socket
// erisimi yalnizca muvon-deployer'da kalir; admin bu RPC ile sinirli bir
// yuzeyden gecer.
type DeployerServiceServer interface {
	// ListContainers active + son acılmış container'ları gosterir. Filtreler
	// ister managed-only ister tum container'lar icin uygulanir. Admin UI'in
	// "Live tail" picker'i bunu cagirir.
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	// GetContainer tek bir container icin durum + label snapshot'ini doner.
	GetContainer(context.Context, *GetContainerRequest) (*ContainerDetail, error)
	// StreamContainerLogs Docker daemon'a `?follow=1&timestamps=1` ile baglanir,
	// multiplexed stream'i demuks edip her satiri ayri bir mesaj olarak yollar.
	// Yavas tuketici icin sunucu drop-oldest backpressure uygular ve sentetik
	// bir "[muvon] dropped N lines" satiri ile kayip bilgisini akıtır.
	StreamContainerLogs(*StreamContainerLogsRequest, grpc.ServerStreamingServer[ContainerLogChunk]) error
	// Health basit bir liveness probe; admin UI deployer down banner'ini
	// bunun başarısızlığına bağlar.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedDeployerServiceServer()
}

// UnimplementedDeployerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeployerServiceServer struct{}

func (UnimplementedDeployerServiceServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedDeployerServiceServer) GetContainer(context.Context, *GetContainerRequest) (*ContainerDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainer not implemented")
}
func (UnimplementedDeployerServiceServer) StreamContainerLogs(*StreamContainerLogsRequest, grpc.ServerStreamingServer[ContainerLogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamContainerLogs not implemented")
}
func (UnimplementedDeployerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedDeployerServiceServer) mustEmbedUnimplementedDeployerServiceServer() {}
func (UnimplementedDeployerServiceServer) testEmbeddedByValue()                         {}

// UnsafeDeployerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeployerServiceServer will
// result in compilation errors.
type UnsafeDeployerServiceServer interface {
	mustEmbedUnimplementedDeployerServiceServer()
}

func RegisterDeployerServiceServer(s grpc.ServiceRegistrar, srv DeployerServiceServer) {
	// If the following call panics, it indicates UnimplementedDeployerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeployerService_ServiceDesc, srv)
}

func _DeployerService_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_GetContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).GetContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_GetContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).GetContainer(ctx, req.(*GetContainerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeployerService_StreamContainerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamContainerLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeployerServiceServer).StreamContainerLogs(m, &grpc.GenericServerStream[StreamContainerLogsRequest, ContainerLogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeployerService_StreamContainerLogsServer = grpc.ServerStreamingServer[ContainerLogChunk]

func _DeployerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeployerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeployerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeployerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeployerService_ServiceDesc is the grpc.ServiceDesc for DeployerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeployerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "deployerpb.DeployerService",
	HandlerType: (*DeployerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContainers",
			Handler:    _DeployerService_ListContainers_Handler,
		},
		{
			MethodName: "GetContainer",
			Handler:    _DeployerService_GetContainer_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _DeployerService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamContainerLogs",
			Handler:       _DeployerService_StreamContainerLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/deployerpb/deployer.proto",
}
