// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/wafpb/waf.proto

package wafpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	RawQuery      string                 `protobuf:"bytes,6,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // flattened: key -> "v1, v2"
	Body          []byte                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	ContentType   string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	RouteId       int32                  `protobuf:"varint,10,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	DetectionOnly bool                   `protobuf:"varint,11,opt,name=detection_only,json=detectionOnly,proto3" json:"detection_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{0}
}

func (x *InspectRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InspectRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *InspectRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *InspectRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InspectRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *InspectRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *InspectRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InspectRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InspectRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InspectRequest) GetRouteId() int32 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *InspectRequest) GetDetectionOnly() bool {
	if x != nil {
		return x.DetectionOnly
	}
	return false
}

type InspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // allow, log, rate_limit, block, temp_ban, ban
	RequestScore  int32                  `protobuf:"varint,2,opt,name=request_score,json=requestScore,proto3" json:"request_score,omitempty"`
	IpScore       float64                `protobuf:"fixed64,3,opt,name=ip_score,json=ipScore,proto3" json:"ip_score,omitempty"`
	Matches       []*RuleMatch           `protobuf:"bytes,4,rep,name=matches,proto3" json:"matches,omitempty"`
	BlockReason   string                 `protobuf:"bytes,5,opt,name=block_reason,json=blockReason,proto3" json:"block_reason,omitempty"`
	DetectionOnly bool                   `protobuf:"varint,6,opt,name=detection_only,json=detectionOnly,proto3" json:"detection_only,omitempty"`
	ProcessingUs  int64                  `protobuf:"varint,7,opt,name=processing_us,json=processingUs,proto3" json:"processing_us,omitempty"` // microseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{1}
}

func (x *InspectResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InspectResponse) GetRequestScore() int32 {
	if x != nil {
		return x.RequestScore
	}
	return 0
}

func (x *InspectResponse) GetIpScore() float64 {
	if x != nil {
		return x.IpScore
	}
	return 0
}

func (x *InspectResponse) GetMatches() []*RuleMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *InspectResponse) GetBlockReason() string {
	if x != nil {
		return x.BlockReason
	}
	return ""
}

func (x *InspectResponse) GetDetectionOnly() bool {
	if x != nil {
		return x.DetectionOnly
	}
	return false
}

func (x *InspectResponse) GetProcessingUs() int64 {
	if x != nil {
		return x.ProcessingUs
	}
	return 0
}

type RuleMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int32                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Severity      int32                  `protobuf:"varint,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Field         string                 `protobuf:"bytes,5,opt,name=field,proto3" json:"field,omitempty"`
	Snippet       string                 `protobuf:"bytes,6,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleMatch) Reset() {
	*x = RuleMatch{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleMatch) ProtoMessage() {}

func (x *RuleMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleMatch.ProtoReflect.Descriptor instead.
func (*RuleMatch) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{2}
}

func (x *RuleMatch) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *RuleMatch) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RuleMatch) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *RuleMatch) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *RuleMatch) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RuleMatch) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type BanIPRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ip              string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"` // 0 = permanent
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BanIPRequest) Reset() {
	*x = BanIPRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanIPRequest) ProtoMessage() {}

func (x *BanIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanIPRequest.ProtoReflect.Descriptor instead.
func (*BanIPRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{3}
}

func (x *BanIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BanIPRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BanIPRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type BanIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanIPResponse) Reset() {
	*x = BanIPResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanIPResponse) ProtoMessage() {}

func (x *BanIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanIPResponse.ProtoReflect.Descriptor instead.
func (*BanIPResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{4}
}

type UnbanIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanIPRequest) Reset() {
	*x = UnbanIPRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanIPRequest) ProtoMessage() {}

func (x *UnbanIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanIPRequest.ProtoReflect.Descriptor instead.
func (*UnbanIPRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{5}
}

func (x *UnbanIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type UnbanIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanIPResponse) Reset() {
	*x = UnbanIPResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanIPResponse) ProtoMessage() {}

func (x *UnbanIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanIPResponse.ProtoReflect.Descriptor instead.
func (*UnbanIPResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{6}
}

type WhitelistIPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistIPRequest) Reset() {
	*x = WhitelistIPRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistIPRequest) ProtoMessage() {}

func (x *WhitelistIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistIPRequest.ProtoReflect.Descriptor instead.
func (*WhitelistIPRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{7}
}

func (x *WhitelistIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type WhitelistIPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhitelistIPResponse) Reset() {
	*x = WhitelistIPResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhitelistIPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistIPResponse) ProtoMessage() {}

func (x *WhitelistIPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistIPResponse.ProtoReflect.Descriptor instead.
func (*WhitelistIPResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{8}
}

type RemoveWhitelistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWhitelistRequest) Reset() {
	*x = RemoveWhitelistRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWhitelistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistRequest) ProtoMessage() {}

func (x *RemoveWhitelistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistRequest.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveWhitelistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RemoveWhitelistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveWhitelistResponse) Reset() {
	*x = RemoveWhitelistResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveWhitelistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveWhitelistResponse) ProtoMessage() {}

func (x *RemoveWhitelistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveWhitelistResponse.ProtoReflect.Descriptor instead.
func (*RemoveWhitelistResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{10}
}

type ListIPStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPStatesRequest) Reset() {
	*x = ListIPStatesRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPStatesRequest) ProtoMessage() {}

func (x *ListIPStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPStatesRequest.ProtoReflect.Descriptor instead.
func (*ListIPStatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{11}
}

type ListIPStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*IPStateEntry        `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIPStatesResponse) Reset() {
	*x = ListIPStatesResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIPStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIPStatesResponse) ProtoMessage() {}

func (x *ListIPStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIPStatesResponse.ProtoReflect.Descriptor instead.
func (*ListIPStatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{12}
}

func (x *ListIPStatesResponse) GetStates() []*IPStateEntry {
	if x != nil {
		return x.States
	}
	return nil
}

type IPStateEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ip              string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Banned          bool                   `protobuf:"varint,2,opt,name=banned,proto3" json:"banned,omitempty"`
	Whitelisted     bool                   `protobuf:"varint,3,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	CumulativeScore float64                `protobuf:"fixed64,4,opt,name=cumulative_score,json=cumulativeScore,proto3" json:"cumulative_score,omitempty"`
	BanReason       string                 `protobuf:"bytes,5,opt,name=ban_reason,json=banReason,proto3" json:"ban_reason,omitempty"`
	LastSeen        string                 `protobuf:"bytes,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // RFC3339
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IPStateEntry) Reset() {
	*x = IPStateEntry{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPStateEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPStateEntry) ProtoMessage() {}

func (x *IPStateEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPStateEntry.ProtoReflect.Descriptor instead.
func (*IPStateEntry) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{13}
}

func (x *IPStateEntry) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPStateEntry) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *IPStateEntry) GetWhitelisted() bool {
	if x != nil {
		return x.Whitelisted
	}
	return false
}

func (x *IPStateEntry) GetCumulativeScore() float64 {
	if x != nil {
		return x.CumulativeScore
	}
	return 0
}

func (x *IPStateEntry) GetBanReason() string {
	if x != nil {
		return x.BanReason
	}
	return ""
}

func (x *IPStateEntry) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	IsRegex       bool                   `protobuf:"varint,3,opt,name=is_regex,json=isRegex,proto3" json:"is_regex,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Severity      int32                  `protobuf:"varint,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{14}
}

func (x *Rule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rule) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Rule) GetIsRegex() bool {
	if x != nil {
		return x.IsRegex
	}
	return false
}

func (x *Rule) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Rule) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Rule) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Rule) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // filter
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{15}
}

func (x *ListRulesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListRulesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{16}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	IsRegex       bool                   `protobuf:"varint,2,opt,name=is_regex,json=isRegex,proto3" json:"is_regex,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Severity      int32                  `protobuf:"varint,4,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{17}
}

func (x *CreateRuleRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *CreateRuleRequest) GetIsRegex() bool {
	if x != nil {
		return x.IsRegex
	}
	return false
}

func (x *CreateRuleRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateRuleRequest) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *CreateRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	IsRegex       bool                   `protobuf:"varint,3,opt,name=is_regex,json=isRegex,proto3" json:"is_regex,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Severity      int32                  `protobuf:"varint,5,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRuleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRuleRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *UpdateRuleRequest) GetIsRegex() bool {
	if x != nil {
		return x.IsRegex
	}
	return false
}

func (x *UpdateRuleRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateRuleRequest) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *UpdateRuleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRuleRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRuleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{20}
}

type ImportRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*CreateRuleRequest   `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRulesRequest) Reset() {
	*x = ImportRulesRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRulesRequest) ProtoMessage() {}

func (x *ImportRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRulesRequest.ProtoReflect.Descriptor instead.
func (*ImportRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{21}
}

func (x *ImportRulesRequest) GetRules() []*CreateRuleRequest {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ImportRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imported      int32                  `protobuf:"varint,1,opt,name=imported,proto3" json:"imported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRulesResponse) Reset() {
	*x = ImportRulesResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRulesResponse) ProtoMessage() {}

func (x *ImportRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRulesResponse.ProtoReflect.Descriptor instead.
func (*ImportRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{22}
}

func (x *ImportRulesResponse) GetImported() int32 {
	if x != nil {
		return x.Imported
	}
	return 0
}

type Exclusion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleId        int32                  `protobuf:"varint,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RouteId       int32                  `protobuf:"varint,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Parameter     string                 `protobuf:"bytes,5,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exclusion) Reset() {
	*x = Exclusion{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exclusion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exclusion) ProtoMessage() {}

func (x *Exclusion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exclusion.ProtoReflect.Descriptor instead.
func (*Exclusion) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{23}
}

func (x *Exclusion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exclusion) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *Exclusion) GetRouteId() int32 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *Exclusion) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Exclusion) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

type ListExclusionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExclusionsRequest) Reset() {
	*x = ListExclusionsRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExclusionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExclusionsRequest) ProtoMessage() {}

func (x *ListExclusionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExclusionsRequest.ProtoReflect.Descriptor instead.
func (*ListExclusionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{24}
}

type ListExclusionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exclusions    []*Exclusion           `protobuf:"bytes,1,rep,name=exclusions,proto3" json:"exclusions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExclusionsResponse) Reset() {
	*x = ListExclusionsResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExclusionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExclusionsResponse) ProtoMessage() {}

func (x *ListExclusionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExclusionsResponse.ProtoReflect.Descriptor instead.
func (*ListExclusionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{25}
}

func (x *ListExclusionsResponse) GetExclusions() []*Exclusion {
	if x != nil {
		return x.Exclusions
	}
	return nil
}

type CreateExclusionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        int32                  `protobuf:"varint,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RouteId       int32                  `protobuf:"varint,2,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Parameter     string                 `protobuf:"bytes,4,opt,name=parameter,proto3" json:"parameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExclusionRequest) Reset() {
	*x = CreateExclusionRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExclusionRequest) ProtoMessage() {}

func (x *CreateExclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExclusionRequest.ProtoReflect.Descriptor instead.
func (*CreateExclusionRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{26}
}

func (x *CreateExclusionRequest) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *CreateExclusionRequest) GetRouteId() int32 {
	if x != nil {
		return x.RouteId
	}
	return 0
}

func (x *CreateExclusionRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateExclusionRequest) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

type DeleteExclusionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExclusionRequest) Reset() {
	*x = DeleteExclusionRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExclusionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExclusionRequest) ProtoMessage() {}

func (x *DeleteExclusionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExclusionRequest.ProtoReflect.Descriptor instead.
func (*DeleteExclusionRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteExclusionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteExclusionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExclusionResponse) Reset() {
	*x = DeleteExclusionResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExclusionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExclusionResponse) ProtoMessage() {}

func (x *DeleteExclusionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExclusionResponse.ProtoReflect.Descriptor instead.
func (*DeleteExclusionResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{28}
}

type SearchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientIp      string                 `protobuf:"bytes,1,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"` // RFC3339
	To            string                 `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventsRequest) Reset() {
	*x = SearchEventsRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventsRequest) ProtoMessage() {}

func (x *SearchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventsRequest.ProtoReflect.Descriptor instead.
func (*SearchEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{29}
}

func (x *SearchEventsRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SearchEventsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SearchEventsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SearchEventsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SearchEventsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SearchEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchEventsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*WafEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEventsResponse) Reset() {
	*x = SearchEventsResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEventsResponse) ProtoMessage() {}

func (x *SearchEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEventsResponse.ProtoReflect.Descriptor instead.
func (*SearchEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{30}
}

func (x *SearchEventsResponse) GetEvents() []*WafEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *SearchEventsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type WafEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ClientIp      string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	RequestScore  int32                  `protobuf:"varint,7,opt,name=request_score,json=requestScore,proto3" json:"request_score,omitempty"`
	IpScore       float64                `protobuf:"fixed64,8,opt,name=ip_score,json=ipScore,proto3" json:"ip_score,omitempty"`
	Action        string                 `protobuf:"bytes,9,opt,name=action,proto3" json:"action,omitempty"`
	MatchedRules  string                 `protobuf:"bytes,10,opt,name=matched_rules,json=matchedRules,proto3" json:"matched_rules,omitempty"` // JSON
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WafEvent) Reset() {
	*x = WafEvent{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WafEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WafEvent) ProtoMessage() {}

func (x *WafEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WafEvent.ProtoReflect.Descriptor instead.
func (*WafEvent) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{31}
}

func (x *WafEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WafEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WafEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *WafEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *WafEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *WafEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WafEvent) GetRequestScore() int32 {
	if x != nil {
		return x.RequestScore
	}
	return 0
}

func (x *WafEvent) GetIpScore() float64 {
	if x != nil {
		return x.IpScore
	}
	return 0
}

func (x *WafEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *WafEvent) GetMatchedRules() string {
	if x != nil {
		return x.MatchedRules
	}
	return ""
}

func (x *WafEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{32}
}

func (x *GetStatsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetStatsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalEvents   int32                  `protobuf:"varint,1,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	TotalBlocked  int32                  `protobuf:"varint,2,opt,name=total_blocked,json=totalBlocked,proto3" json:"total_blocked,omitempty"`
	UniqueIps     int32                  `protobuf:"varint,3,opt,name=unique_ips,json=uniqueIps,proto3" json:"unique_ips,omitempty"`
	TopCategories []*CategoryCount       `protobuf:"bytes,4,rep,name=top_categories,json=topCategories,proto3" json:"top_categories,omitempty"`
	TopIps        []*IPCount             `protobuf:"bytes,5,rep,name=top_ips,json=topIps,proto3" json:"top_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{33}
}

func (x *GetStatsResponse) GetTotalEvents() int32 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *GetStatsResponse) GetTotalBlocked() int32 {
	if x != nil {
		return x.TotalBlocked
	}
	return 0
}

func (x *GetStatsResponse) GetUniqueIps() int32 {
	if x != nil {
		return x.UniqueIps
	}
	return 0
}

func (x *GetStatsResponse) GetTopCategories() []*CategoryCount {
	if x != nil {
		return x.TopCategories
	}
	return nil
}

func (x *GetStatsResponse) GetTopIps() []*IPCount {
	if x != nil {
		return x.TopIps
	}
	return nil
}

type CategoryCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryCount) Reset() {
	*x = CategoryCount{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryCount) ProtoMessage() {}

func (x *CategoryCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryCount.ProtoReflect.Descriptor instead.
func (*CategoryCount) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{34}
}

func (x *CategoryCount) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type IPCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPCount) Reset() {
	*x = IPCount{}
	mi := &file_proto_wafpb_waf_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPCount) ProtoMessage() {}

func (x *IPCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wafpb_waf_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPCount.ProtoReflect.Descriptor instead.
func (*IPCount) Descriptor() ([]byte, []int) {
	return file_proto_wafpb_waf_proto_rawDescGZIP(), []int{35}
}

func (x *IPCount) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IPCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_wafpb_waf_proto protoreflect.FileDescriptor

const file_proto_wafpb_waf_proto_rawDesc = "" +
	"\n" +
	"\x15proto/wafpb/waf.proto\x12\x05wafpb\"\x9c\x03\n" +
	"\x0eInspectRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x06 \x01(\tR\brawQuery\x12<\n" +
	"\aheaders\x18\a \x03(\v2\".wafpb.InspectRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\b \x01(\fR\x04body\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12\x19\n" +
	"\broute_id\x18\n" +
	" \x01(\x05R\arouteId\x12%\n" +
	"\x0edetection_only\x18\v \x01(\bR\rdetectionOnly\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\x0fInspectResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12#\n" +
	"\rrequest_score\x18\x02 \x01(\x05R\frequestScore\x12\x19\n" +
	"\bip_score\x18\x03 \x01(\x01R\aipScore\x12*\n" +
	"\amatches\x18\x04 \x03(\v2\x10.wafpb.RuleMatchR\amatches\x12!\n" +
	"\fblock_reason\x18\x05 \x01(\tR\vblockReason\x12%\n" +
	"\x0edetection_only\x18\x06 \x01(\bR\rdetectionOnly\x12#\n" +
	"\rprocessing_us\x18\a \x01(\x03R\fprocessingUs\"\xa8\x01\n" +
	"\tRuleMatch\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x05R\x06ruleId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\x05R\bseverity\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x14\n" +
	"\x05field\x18\x05 \x01(\tR\x05field\x12\x18\n" +
	"\asnippet\x18\x06 \x01(\tR\asnippet\"a\n" +
	"\fBanIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\"\x0f\n" +
	"\rBanIPResponse\" \n" +
	"\x0eUnbanIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x11\n" +
	"\x0fUnbanIPResponse\"$\n" +
	"\x12WhitelistIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x15\n" +
	"\x13WhitelistIPResponse\"(\n" +
	"\x16RemoveWhitelistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"\x19\n" +
	"\x17RemoveWhitelistResponse\"\x15\n" +
	"\x13ListIPStatesRequest\"C\n" +
	"\x14ListIPStatesResponse\x12+\n" +
	"\x06states\x18\x01 \x03(\v2\x13.wafpb.IPStateEntryR\x06states\"\xbf\x01\n" +
	"\fIPStateEntry\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06banned\x18\x02 \x01(\bR\x06banned\x12 \n" +
	"\vwhitelisted\x18\x03 \x01(\bR\vwhitelisted\x12)\n" +
	"\x10cumulative_score\x18\x04 \x01(\x01R\x0fcumulativeScore\x12\x1d\n" +
	"\n" +
	"ban_reason\x18\x05 \x01(\tR\tbanReason\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\tR\blastSeen\"\x80\x02\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x19\n" +
	"\bis_regex\x18\x03 \x01(\bR\aisRegex\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\x05R\bseverity\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"O\n" +
	"\x10ListRulesRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"6\n" +
	"\x11ListRulesResponse\x12!\n" +
	"\x05rules\x18\x01 \x03(\v2\v.wafpb.RuleR\x05rules\"\xa2\x01\n" +
	"\x11CreateRuleRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x19\n" +
	"\bis_regex\x18\x02 \x01(\bR\aisRegex\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\x05R\bseverity\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xcf\x01\n" +
	"\x11UpdateRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x19\n" +
	"\bis_regex\x18\x03 \x01(\bR\aisRegex\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\x05R\bseverity\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"#\n" +
	"\x11DeleteRuleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x14\n" +
	"\x12DeleteRuleResponse\"D\n" +
	"\x12ImportRulesRequest\x12.\n" +
	"\x05rules\x18\x01 \x03(\v2\x18.wafpb.CreateRuleRequestR\x05rules\"1\n" +
	"\x13ImportRulesResponse\x12\x1a\n" +
	"\bimported\x18\x01 \x01(\x05R\bimported\"\x89\x01\n" +
	"\tExclusion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\x05R\x06ruleId\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\x05R\arouteId\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x1c\n" +
	"\tparameter\x18\x05 \x01(\tR\tparameter\"\x17\n" +
	"\x15ListExclusionsRequest\"J\n" +
	"\x16ListExclusionsResponse\x120\n" +
	"\n" +
	"exclusions\x18\x01 \x03(\v2\x10.wafpb.ExclusionR\n" +
	"exclusions\"\x86\x01\n" +
	"\x16CreateExclusionRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\x05R\x06ruleId\x12\x19\n" +
	"\broute_id\x18\x02 \x01(\x05R\arouteId\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1c\n" +
	"\tparameter\x18\x04 \x01(\tR\tparameter\"(\n" +
	"\x16DeleteExclusionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x19\n" +
	"\x17DeleteExclusionResponse\"\xb0\x01\n" +
	"\x13SearchEventsRequest\x12\x1b\n" +
	"\tclient_ip\x18\x01 \x01(\tR\bclientIp\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\tR\x02to\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\a \x01(\x05R\x06offset\"U\n" +
	"\x14SearchEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.wafpb.WafEventR\x06events\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb2\x02\n" +
	"\bWafEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12#\n" +
	"\rrequest_score\x18\a \x01(\x05R\frequestScore\x12\x19\n" +
	"\bip_score\x18\b \x01(\x01R\aipScore\x12\x16\n" +
	"\x06action\x18\t \x01(\tR\x06action\x12#\n" +
	"\rmatched_rules\x18\n" +
	" \x01(\tR\fmatchedRules\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"5\n" +
	"\x0fGetStatsRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"\xdf\x01\n" +
	"\x10GetStatsResponse\x12!\n" +
	"\ftotal_events\x18\x01 \x01(\x05R\vtotalEvents\x12#\n" +
	"\rtotal_blocked\x18\x02 \x01(\x05R\ftotalBlocked\x12\x1d\n" +
	"\n" +
	"unique_ips\x18\x03 \x01(\x05R\tuniqueIps\x12;\n" +
	"\x0etop_categories\x18\x04 \x03(\v2\x14.wafpb.CategoryCountR\rtopCategories\x12'\n" +
	"\atop_ips\x18\x05 \x03(\v2\x0e.wafpb.IPCountR\x06topIps\"A\n" +
	"\rCategoryCount\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"/\n" +
	"\aIPCount\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xb3\b\n" +
	"\n" +
	"WafService\x128\n" +
	"\aInspect\x12\x15.wafpb.InspectRequest\x1a\x16.wafpb.InspectResponse\x122\n" +
	"\x05BanIP\x12\x13.wafpb.BanIPRequest\x1a\x14.wafpb.BanIPResponse\x128\n" +
	"\aUnbanIP\x12\x15.wafpb.UnbanIPRequest\x1a\x16.wafpb.UnbanIPResponse\x12D\n" +
	"\vWhitelistIP\x12\x19.wafpb.WhitelistIPRequest\x1a\x1a.wafpb.WhitelistIPResponse\x12P\n" +
	"\x0fRemoveWhitelist\x12\x1d.wafpb.RemoveWhitelistRequest\x1a\x1e.wafpb.RemoveWhitelistResponse\x12G\n" +
	"\fListIPStates\x12\x1a.wafpb.ListIPStatesRequest\x1a\x1b.wafpb.ListIPStatesResponse\x12>\n" +
	"\tListRules\x12\x17.wafpb.ListRulesRequest\x1a\x18.wafpb.ListRulesResponse\x123\n" +
	"\n" +
	"CreateRule\x12\x18.wafpb.CreateRuleRequest\x1a\v.wafpb.Rule\x123\n" +
	"\n" +
	"UpdateRule\x12\x18.wafpb.UpdateRuleRequest\x1a\v.wafpb.Rule\x12A\n" +
	"\n" +
	"DeleteRule\x12\x18.wafpb.DeleteRuleRequest\x1a\x19.wafpb.DeleteRuleResponse\x12D\n" +
	"\vImportRules\x12\x19.wafpb.ImportRulesRequest\x1a\x1a.wafpb.ImportRulesResponse\x12M\n" +
	"\x0eListExclusions\x12\x1c.wafpb.ListExclusionsRequest\x1a\x1d.wafpb.ListExclusionsResponse\x12B\n" +
	"\x0fCreateExclusion\x12\x1d.wafpb.CreateExclusionRequest\x1a\x10.wafpb.Exclusion\x12P\n" +
	"\x0fDeleteExclusion\x12\x1d.wafpb.DeleteExclusionRequest\x1a\x1e.wafpb.DeleteExclusionResponse\x12G\n" +
	"\fSearchEvents\x12\x1a.wafpb.SearchEventsRequest\x1a\x1b.wafpb.SearchEventsResponse\x12;\n" +
	"\bGetStats\x12\x16.wafpb.GetStatsRequest\x1a\x17.wafpb.GetStatsResponseB\x14Z\x12dialog/proto/wafpbb\x06proto3"

var (
	file_proto_wafpb_waf_proto_rawDescOnce sync.Once
	file_proto_wafpb_waf_proto_rawDescData []byte
)

func file_proto_wafpb_waf_proto_rawDescGZIP() []byte {
	file_proto_wafpb_waf_proto_rawDescOnce.Do(func() {
		file_proto_wafpb_waf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wafpb_waf_proto_rawDesc), len(file_proto_wafpb_waf_proto_rawDesc)))
	})
	return file_proto_wafpb_waf_proto_rawDescData
}

var file_proto_wafpb_waf_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_proto_wafpb_waf_proto_goTypes = []any{
	(*InspectRequest)(nil),          // 0: wafpb.InspectRequest
	(*InspectResponse)(nil),         // 1: wafpb.InspectResponse
	(*RuleMatch)(nil),               // 2: wafpb.RuleMatch
	(*BanIPRequest)(nil),            // 3: wafpb.BanIPRequest
	(*BanIPResponse)(nil),           // 4: wafpb.BanIPResponse
	(*UnbanIPRequest)(nil),          // 5: wafpb.UnbanIPRequest
	(*UnbanIPResponse)(nil),         // 6: wafpb.UnbanIPResponse
	(*WhitelistIPRequest)(nil),      // 7: wafpb.WhitelistIPRequest
	(*WhitelistIPResponse)(nil),     // 8: wafpb.WhitelistIPResponse
	(*RemoveWhitelistRequest)(nil),  // 9: wafpb.RemoveWhitelistRequest
	(*RemoveWhitelistResponse)(nil), // 10: wafpb.RemoveWhitelistResponse
	(*ListIPStatesRequest)(nil),     // 11: wafpb.ListIPStatesRequest
	(*ListIPStatesResponse)(nil),    // 12: wafpb.ListIPStatesResponse
	(*IPStateEntry)(nil),            // 13: wafpb.IPStateEntry
	(*Rule)(nil),                    // 14: wafpb.Rule
	(*ListRulesRequest)(nil),        // 15: wafpb.ListRulesRequest
	(*ListRulesResponse)(nil),       // 16: wafpb.ListRulesResponse
	(*CreateRuleRequest)(nil),       // 17: wafpb.CreateRuleRequest
	(*UpdateRuleRequest)(nil),       // 18: wafpb.UpdateRuleRequest
	(*DeleteRuleRequest)(nil),       // 19: wafpb.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),      // 20: wafpb.DeleteRuleResponse
	(*ImportRulesRequest)(nil),      // 21: wafpb.ImportRulesRequest
	(*ImportRulesResponse)(nil),     // 22: wafpb.ImportRulesResponse
	(*Exclusion)(nil),               // 23: wafpb.Exclusion
	(*ListExclusionsRequest)(nil),   // 24: wafpb.ListExclusionsRequest
	(*ListExclusionsResponse)(nil),  // 25: wafpb.ListExclusionsResponse
	(*CreateExclusionRequest)(nil),  // 26: wafpb.CreateExclusionRequest
	(*DeleteExclusionRequest)(nil),  // 27: wafpb.DeleteExclusionRequest
	(*DeleteExclusionResponse)(nil), // 28: wafpb.DeleteExclusionResponse
	(*SearchEventsRequest)(nil),     // 29: wafpb.SearchEventsRequest
	(*SearchEventsResponse)(nil),    // 30: wafpb.SearchEventsResponse
	(*WafEvent)(nil),                // 31: wafpb.WafEvent
	(*GetStatsRequest)(nil),         // 32: wafpb.GetStatsRequest
	(*GetStatsResponse)(nil),        // 33: wafpb.GetStatsResponse
	(*CategoryCount)(nil),           // 34: wafpb.CategoryCount
	(*IPCount)(nil),                 // 35: wafpb.IPCount
	nil,                             // 36: wafpb.InspectRequest.HeadersEntry
}
var file_proto_wafpb_waf_proto_depIdxs = []int32{
	36, // 0: wafpb.InspectRequest.headers:type_name -> wafpb.InspectRequest.HeadersEntry
	2,  // 1: wafpb.InspectResponse.matches:type_name -> wafpb.RuleMatch
	13, // 2: wafpb.ListIPStatesResponse.states:type_name -> wafpb.IPStateEntry
	14, // 3: wafpb.ListRulesResponse.rules:type_name -> wafpb.Rule
	17, // 4: wafpb.ImportRulesRequest.rules:type_name -> wafpb.CreateRuleRequest
	23, // 5: wafpb.ListExclusionsResponse.exclusions:type_name -> wafpb.Exclusion
	31, // 6: wafpb.SearchEventsResponse.events:type_name -> wafpb.WafEvent
	34, // 7: wafpb.GetStatsResponse.top_categories:type_name -> wafpb.CategoryCount
	35, // 8: wafpb.GetStatsResponse.top_ips:type_name -> wafpb.IPCount
	0,  // 9: wafpb.WafService.Inspect:input_type -> wafpb.InspectRequest
	3,  // 10: wafpb.WafService.BanIP:input_type -> wafpb.BanIPRequest
	5,  // 11: wafpb.WafService.UnbanIP:input_type -> wafpb.UnbanIPRequest
	7,  // 12: wafpb.WafService.WhitelistIP:input_type -> wafpb.WhitelistIPRequest
	9,  // 13: wafpb.WafService.RemoveWhitelist:input_type -> wafpb.RemoveWhitelistRequest
	11, // 14: wafpb.WafService.ListIPStates:input_type -> wafpb.ListIPStatesRequest
	15, // 15: wafpb.WafService.ListRules:input_type -> wafpb.ListRulesRequest
	17, // 16: wafpb.WafService.CreateRule:input_type -> wafpb.CreateRuleRequest
	18, // 17: wafpb.WafService.UpdateRule:input_type -> wafpb.UpdateRuleRequest
	19, // 18: wafpb.WafService.DeleteRule:input_type -> wafpb.DeleteRuleRequest
	21, // 19: wafpb.WafService.ImportRules:input_type -> wafpb.ImportRulesRequest
	24, // 20: wafpb.WafService.ListExclusions:input_type -> wafpb.ListExclusionsRequest
	26, // 21: wafpb.WafService.CreateExclusion:input_type -> wafpb.CreateExclusionRequest
	27, // 22: wafpb.WafService.DeleteExclusion:input_type -> wafpb.DeleteExclusionRequest
	29, // 23: wafpb.WafService.SearchEvents:input_type -> wafpb.SearchEventsRequest
	32, // 24: wafpb.WafService.GetStats:input_type -> wafpb.GetStatsRequest
	1,  // 25: wafpb.WafService.Inspect:output_type -> wafpb.InspectResponse
	4,  // 26: wafpb.WafService.BanIP:output_type -> wafpb.BanIPResponse
	6,  // 27: wafpb.WafService.UnbanIP:output_type -> wafpb.UnbanIPResponse
	8,  // 28: wafpb.WafService.WhitelistIP:output_type -> wafpb.WhitelistIPResponse
	10, // 29: wafpb.WafService.RemoveWhitelist:output_type -> wafpb.RemoveWhitelistResponse
	12, // 30: wafpb.WafService.ListIPStates:output_type -> wafpb.ListIPStatesResponse
	16, // 31: wafpb.WafService.ListRules:output_type -> wafpb.ListRulesResponse
	14, // 32: wafpb.WafService.CreateRule:output_type -> wafpb.Rule
	14, // 33: wafpb.WafService.UpdateRule:output_type -> wafpb.Rule
	20, // 34: wafpb.WafService.DeleteRule:output_type -> wafpb.DeleteRuleResponse
	22, // 35: wafpb.WafService.ImportRules:output_type -> wafpb.ImportRulesResponse
	25, // 36: wafpb.WafService.ListExclusions:output_type -> wafpb.ListExclusionsResponse
	23, // 37: wafpb.WafService.CreateExclusion:output_type -> wafpb.Exclusion
	28, // 38: wafpb.WafService.DeleteExclusion:output_type -> wafpb.DeleteExclusionResponse
	30, // 39: wafpb.WafService.SearchEvents:output_type -> wafpb.SearchEventsResponse
	33, // 40: wafpb.WafService.GetStats:output_type -> wafpb.GetStatsResponse
	25, // [25:41] is the sub-list for method output_type
	9,  // [9:25] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_wafpb_waf_proto_init() }
func file_proto_wafpb_waf_proto_init() {
	if File_proto_wafpb_waf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wafpb_waf_proto_rawDesc), len(file_proto_wafpb_waf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wafpb_waf_proto_goTypes,
		DependencyIndexes: file_proto_wafpb_waf_proto_depIdxs,
		MessageInfos:      file_proto_wafpb_waf_proto_msgTypes,
	}.Build()
	File_proto_wafpb_waf_proto = out.File
	file_proto_wafpb_waf_proto_goTypes = nil
	file_proto_wafpb_waf_proto_depIdxs = nil
}
