// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/wafpb/waf.proto

package wafpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WafService_Inspect_FullMethodName         = "/wafpb.WafService/Inspect"
	WafService_BanIP_FullMethodName           = "/wafpb.WafService/BanIP"
	WafService_UnbanIP_FullMethodName         = "/wafpb.WafService/UnbanIP"
	WafService_WhitelistIP_FullMethodName     = "/wafpb.WafService/WhitelistIP"
	WafService_RemoveWhitelist_FullMethodName = "/wafpb.WafService/RemoveWhitelist"
	WafService_ListIPStates_FullMethodName    = "/wafpb.WafService/ListIPStates"
	WafService_ListRules_FullMethodName       = "/wafpb.WafService/ListRules"
	WafService_CreateRule_FullMethodName      = "/wafpb.WafService/CreateRule"
	WafService_UpdateRule_FullMethodName      = "/wafpb.WafService/UpdateRule"
	WafService_DeleteRule_FullMethodName      = "/wafpb.WafService/DeleteRule"
	WafService_ImportRules_FullMethodName     = "/wafpb.WafService/ImportRules"
	WafService_ListExclusions_FullMethodName  = "/wafpb.WafService/ListExclusions"
	WafService_CreateExclusion_FullMethodName = "/wafpb.WafService/CreateExclusion"
	WafService_DeleteExclusion_FullMethodName = "/wafpb.WafService/DeleteExclusion"
	WafService_SearchEvents_FullMethodName    = "/wafpb.WafService/SearchEvents"
	WafService_GetStats_FullMethodName        = "/wafpb.WafService/GetStats"
)

// WafServiceClient is the client API for WafService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WafService — muWAF'in gRPC API'si.
// MUVON her gelen HTTP istegini bu servise sorar.
type WafServiceClient interface {
	// Inspect: gelen HTTP istegini denetle, skor ve aksiyon don.
	Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error)
	// --- IP Yonetimi ---
	BanIP(ctx context.Context, in *BanIPRequest, opts ...grpc.CallOption) (*BanIPResponse, error)
	UnbanIP(ctx context.Context, in *UnbanIPRequest, opts ...grpc.CallOption) (*UnbanIPResponse, error)
	WhitelistIP(ctx context.Context, in *WhitelistIPRequest, opts ...grpc.CallOption) (*WhitelistIPResponse, error)
	RemoveWhitelist(ctx context.Context, in *RemoveWhitelistRequest, opts ...grpc.CallOption) (*RemoveWhitelistResponse, error)
	ListIPStates(ctx context.Context, in *ListIPStatesRequest, opts ...grpc.CallOption) (*ListIPStatesResponse, error)
	// --- Kural Yonetimi ---
	ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error)
	CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*Rule, error)
	UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*Rule, error)
	DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error)
	ImportRules(ctx context.Context, in *ImportRulesRequest, opts ...grpc.CallOption) (*ImportRulesResponse, error)
	// --- Exclusion ---
	ListExclusions(ctx context.Context, in *ListExclusionsRequest, opts ...grpc.CallOption) (*ListExclusionsResponse, error)
	CreateExclusion(ctx context.Context, in *CreateExclusionRequest, opts ...grpc.CallOption) (*Exclusion, error)
	DeleteExclusion(ctx context.Context, in *DeleteExclusionRequest, opts ...grpc.CallOption) (*DeleteExclusionResponse, error)
	// --- Event / Stats ---
	SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error)
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
}

type wafServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWafServiceClient(cc grpc.ClientConnInterface) WafServiceClient {
	return &wafServiceClient{cc}
}

func (c *wafServiceClient) Inspect(ctx context.Context, in *InspectRequest, opts ...grpc.CallOption) (*InspectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectResponse)
	err := c.cc.Invoke(ctx, WafService_Inspect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) BanIP(ctx context.Context, in *BanIPRequest, opts ...grpc.CallOption) (*BanIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BanIPResponse)
	err := c.cc.Invoke(ctx, WafService_BanIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) UnbanIP(ctx context.Context, in *UnbanIPRequest, opts ...grpc.CallOption) (*UnbanIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbanIPResponse)
	err := c.cc.Invoke(ctx, WafService_UnbanIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) WhitelistIP(ctx context.Context, in *WhitelistIPRequest, opts ...grpc.CallOption) (*WhitelistIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhitelistIPResponse)
	err := c.cc.Invoke(ctx, WafService_WhitelistIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) RemoveWhitelist(ctx context.Context, in *RemoveWhitelistRequest, opts ...grpc.CallOption) (*RemoveWhitelistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWhitelistResponse)
	err := c.cc.Invoke(ctx, WafService_RemoveWhitelist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) ListIPStates(ctx context.Context, in *ListIPStatesRequest, opts ...grpc.CallOption) (*ListIPStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIPStatesResponse)
	err := c.cc.Invoke(ctx, WafService_ListIPStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) ListRules(ctx context.Context, in *ListRulesRequest, opts ...grpc.CallOption) (*ListRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRulesResponse)
	err := c.cc.Invoke(ctx, WafService_ListRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) CreateRule(ctx context.Context, in *CreateRuleRequest, opts ...grpc.CallOption) (*Rule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rule)
	err := c.cc.Invoke(ctx, WafService_CreateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) UpdateRule(ctx context.Context, in *UpdateRuleRequest, opts ...grpc.CallOption) (*Rule, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Rule)
	err := c.cc.Invoke(ctx, WafService_UpdateRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) DeleteRule(ctx context.Context, in *DeleteRuleRequest, opts ...grpc.CallOption) (*DeleteRuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRuleResponse)
	err := c.cc.Invoke(ctx, WafService_DeleteRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) ImportRules(ctx context.Context, in *ImportRulesRequest, opts ...grpc.CallOption) (*ImportRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportRulesResponse)
	err := c.cc.Invoke(ctx, WafService_ImportRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) ListExclusions(ctx context.Context, in *ListExclusionsRequest, opts ...grpc.CallOption) (*ListExclusionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExclusionsResponse)
	err := c.cc.Invoke(ctx, WafService_ListExclusions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) CreateExclusion(ctx context.Context, in *CreateExclusionRequest, opts ...grpc.CallOption) (*Exclusion, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Exclusion)
	err := c.cc.Invoke(ctx, WafService_CreateExclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) DeleteExclusion(ctx context.Context, in *DeleteExclusionRequest, opts ...grpc.CallOption) (*DeleteExclusionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteExclusionResponse)
	err := c.cc.Invoke(ctx, WafService_DeleteExclusion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) SearchEvents(ctx context.Context, in *SearchEventsRequest, opts ...grpc.CallOption) (*SearchEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEventsResponse)
	err := c.cc.Invoke(ctx, WafService_SearchEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wafServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, WafService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WafServiceServer is the server API for WafService service.
// All implementations must embed UnimplementedWafServiceServer
// for forward compatibility.
//
// WafService — muWAF'in gRPC API'si.
// MUVON her gelen HTTP istegini bu servise sorar.
type WafServiceServer interface {
	// Inspect: gelen HTTP istegini denetle, skor ve aksiyon don.
	Inspect(context.Context, *InspectRequest) (*InspectResponse, error)
	// --- IP Yonetimi ---
	BanIP(context.Context, *BanIPRequest) (*BanIPResponse, error)
	UnbanIP(context.Context, *UnbanIPRequest) (*UnbanIPResponse, error)
	WhitelistIP(context.Context, *WhitelistIPRequest) (*WhitelistIPResponse, error)
	RemoveWhitelist(context.Context, *RemoveWhitelistRequest) (*RemoveWhitelistResponse, error)
	ListIPStates(context.Context, *ListIPStatesRequest) (*ListIPStatesResponse, error)
	// --- Kural Yonetimi ---
	ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error)
	CreateRule(context.Context, *CreateRuleRequest) (*Rule, error)
	UpdateRule(context.Context, *UpdateRuleRequest) (*Rule, error)
	DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error)
	ImportRules(context.Context, *ImportRulesRequest) (*ImportRulesResponse, error)
	// --- Exclusion ---
	ListExclusions(context.Context, *ListExclusionsRequest) (*ListExclusionsResponse, error)
	CreateExclusion(context.Context, *CreateExclusionRequest) (*Exclusion, error)
	DeleteExclusion(context.Context, *DeleteExclusionRequest) (*DeleteExclusionResponse, error)
	// --- Event / Stats ---
	SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error)
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	mustEmbedUnimplementedWafServiceServer()
}

// UnimplementedWafServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWafServiceServer struct{}

func (UnimplementedWafServiceServer) Inspect(context.Context, *InspectRequest) (*InspectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Inspect not implemented")
}
func (UnimplementedWafServiceServer) BanIP(context.Context, *BanIPRequest) (*BanIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BanIP not implemented")
}
func (UnimplementedWafServiceServer) UnbanIP(context.Context, *UnbanIPRequest) (*UnbanIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbanIP not implemented")
}
func (UnimplementedWafServiceServer) WhitelistIP(context.Context, *WhitelistIPRequest) (*WhitelistIPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhitelistIP not implemented")
}
func (UnimplementedWafServiceServer) RemoveWhitelist(context.Context, *RemoveWhitelistRequest) (*RemoveWhitelistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWhitelist not implemented")
}
func (UnimplementedWafServiceServer) ListIPStates(context.Context, *ListIPStatesRequest) (*ListIPStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListIPStates not implemented")
}
func (UnimplementedWafServiceServer) ListRules(context.Context, *ListRulesRequest) (*ListRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRules not implemented")
}
func (UnimplementedWafServiceServer) CreateRule(context.Context, *CreateRuleRequest) (*Rule, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRule not implemented")
}
func (UnimplementedWafServiceServer) UpdateRule(context.Context, *UpdateRuleRequest) (*Rule, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRule not implemented")
}
func (UnimplementedWafServiceServer) DeleteRule(context.Context, *DeleteRuleRequest) (*DeleteRuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRule not implemented")
}
func (UnimplementedWafServiceServer) ImportRules(context.Context, *ImportRulesRequest) (*ImportRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportRules not implemented")
}
func (UnimplementedWafServiceServer) ListExclusions(context.Context, *ListExclusionsRequest) (*ListExclusionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExclusions not implemented")
}
func (UnimplementedWafServiceServer) CreateExclusion(context.Context, *CreateExclusionRequest) (*Exclusion, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExclusion not implemented")
}
func (UnimplementedWafServiceServer) DeleteExclusion(context.Context, *DeleteExclusionRequest) (*DeleteExclusionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteExclusion not implemented")
}
func (UnimplementedWafServiceServer) SearchEvents(context.Context, *SearchEventsRequest) (*SearchEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEvents not implemented")
}
func (UnimplementedWafServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedWafServiceServer) mustEmbedUnimplementedWafServiceServer() {}
func (UnimplementedWafServiceServer) testEmbeddedByValue()                    {}

// UnsafeWafServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WafServiceServer will
// result in compilation errors.
type UnsafeWafServiceServer interface {
	mustEmbedUnimplementedWafServiceServer()
}

func RegisterWafServiceServer(s grpc.ServiceRegistrar, srv WafServiceServer) {
	// If the following call panics, it indicates UnimplementedWafServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WafService_ServiceDesc, srv)
}

func _WafService_Inspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).Inspect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_Inspect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).Inspect(ctx, req.(*InspectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_BanIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BanIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).BanIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_BanIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).BanIP(ctx, req.(*BanIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_UnbanIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbanIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).UnbanIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_UnbanIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).UnbanIP(ctx, req.(*UnbanIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_WhitelistIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhitelistIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).WhitelistIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_WhitelistIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).WhitelistIP(ctx, req.(*WhitelistIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_RemoveWhitelist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWhitelistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).RemoveWhitelist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_RemoveWhitelist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).RemoveWhitelist(ctx, req.(*RemoveWhitelistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_ListIPStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIPStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).ListIPStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_ListIPStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).ListIPStates(ctx, req.(*ListIPStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_ListRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).ListRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_ListRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).ListRules(ctx, req.(*ListRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_CreateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).CreateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_CreateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).CreateRule(ctx, req.(*CreateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_UpdateRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).UpdateRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_UpdateRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).UpdateRule(ctx, req.(*UpdateRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_DeleteRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).DeleteRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_DeleteRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).DeleteRule(ctx, req.(*DeleteRuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_ImportRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).ImportRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_ImportRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).ImportRules(ctx, req.(*ImportRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_ListExclusions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExclusionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).ListExclusions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_ListExclusions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).ListExclusions(ctx, req.(*ListExclusionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_CreateExclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).CreateExclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_CreateExclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).CreateExclusion(ctx, req.(*CreateExclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_DeleteExclusion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExclusionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).DeleteExclusion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_DeleteExclusion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).DeleteExclusion(ctx, req.(*DeleteExclusionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_SearchEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).SearchEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_SearchEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).SearchEvents(ctx, req.(*SearchEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WafService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WafServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WafService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WafServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WafService_ServiceDesc is the grpc.ServiceDesc for WafService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WafService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wafpb.WafService",
	HandlerType: (*WafServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Inspect",
			Handler:    _WafService_Inspect_Handler,
		},
		{
			MethodName: "BanIP",
			Handler:    _WafService_BanIP_Handler,
		},
		{
			MethodName: "UnbanIP",
			Handler:    _WafService_UnbanIP_Handler,
		},
		{
			MethodName: "WhitelistIP",
			Handler:    _WafService_WhitelistIP_Handler,
		},
		{
			MethodName: "RemoveWhitelist",
			Handler:    _WafService_RemoveWhitelist_Handler,
		},
		{
			MethodName: "ListIPStates",
			Handler:    _WafService_ListIPStates_Handler,
		},
		{
			MethodName: "ListRules",
			Handler:    _WafService_ListRules_Handler,
		},
		{
			MethodName: "CreateRule",
			Handler:    _WafService_CreateRule_Handler,
		},
		{
			MethodName: "UpdateRule",
			Handler:    _WafService_UpdateRule_Handler,
		},
		{
			MethodName: "DeleteRule",
			Handler:    _WafService_DeleteRule_Handler,
		},
		{
			MethodName: "ImportRules",
			Handler:    _WafService_ImportRules_Handler,
		},
		{
			MethodName: "ListExclusions",
			Handler:    _WafService_ListExclusions_Handler,
		},
		{
			MethodName: "CreateExclusion",
			Handler:    _WafService_CreateExclusion_Handler,
		},
		{
			MethodName: "DeleteExclusion",
			Handler:    _WafService_DeleteExclusion_Handler,
		},
		{
			MethodName: "SearchEvents",
			Handler:    _WafService_SearchEvents_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _WafService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wafpb/waf.proto",
}
