// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/logpb/log.proto

package logpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogEntry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp           string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339Nano
	Host                string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	ClientIp            string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Method              string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Path                string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	QueryString         string                 `protobuf:"bytes,7,opt,name=query_string,json=queryString,proto3" json:"query_string,omitempty"`
	RequestHeaders      map[string]string      `protobuf:"bytes,8,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseStatus      int32                  `protobuf:"varint,9,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseHeaders     map[string]string      `protobuf:"bytes,10,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseTimeMs      int32                  `protobuf:"varint,11,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	RequestSize         int32                  `protobuf:"varint,12,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`
	ResponseSize        int32                  `protobuf:"varint,13,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	UserAgent           string                 `protobuf:"bytes,14,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Error               string                 `protobuf:"bytes,15,opt,name=error,proto3" json:"error,omitempty"`
	RequestBody         []byte                 `protobuf:"bytes,16,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseBody        []byte                 `protobuf:"bytes,17,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	IsRequestTruncated  bool                   `protobuf:"varint,18,opt,name=is_request_truncated,json=isRequestTruncated,proto3" json:"is_request_truncated,omitempty"`
	IsResponseTruncated bool                   `protobuf:"varint,19,opt,name=is_response_truncated,json=isResponseTruncated,proto3" json:"is_response_truncated,omitempty"`
	// WAF metadata — MUVON, muWAF'tan aldigi sonucu buraya ekler
	WafBlocked     bool   `protobuf:"varint,20,opt,name=waf_blocked,json=wafBlocked,proto3" json:"waf_blocked,omitempty"`
	WafBlockReason string `protobuf:"bytes,21,opt,name=waf_block_reason,json=wafBlockReason,proto3" json:"waf_block_reason,omitempty"`
	WafScore       int32  `protobuf:"varint,22,opt,name=waf_score,json=wafScore,proto3" json:"waf_score,omitempty"`
	WafAction      string `protobuf:"bytes,23,opt,name=waf_action,json=wafAction,proto3" json:"waf_action,omitempty"`
	// Identity enrichment (JWT)
	UserIdentity *UserIdentity `protobuf:"bytes,24,opt,name=user_identity,json=userIdentity,proto3" json:"user_identity,omitempty"`
	// GeoIP enrichment
	Country       string `protobuf:"bytes,25,opt,name=country,proto3" json:"country,omitempty"`
	City          string `protobuf:"bytes,26,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_logpb_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LogEntry) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LogEntry) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogEntry) GetQueryString() string {
	if x != nil {
		return x.QueryString
	}
	return ""
}

func (x *LogEntry) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *LogEntry) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *LogEntry) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *LogEntry) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *LogEntry) GetRequestSize() int32 {
	if x != nil {
		return x.RequestSize
	}
	return 0
}

func (x *LogEntry) GetResponseSize() int32 {
	if x != nil {
		return x.ResponseSize
	}
	return 0
}

func (x *LogEntry) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LogEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogEntry) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *LogEntry) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *LogEntry) GetIsRequestTruncated() bool {
	if x != nil {
		return x.IsRequestTruncated
	}
	return false
}

func (x *LogEntry) GetIsResponseTruncated() bool {
	if x != nil {
		return x.IsResponseTruncated
	}
	return false
}

func (x *LogEntry) GetWafBlocked() bool {
	if x != nil {
		return x.WafBlocked
	}
	return false
}

func (x *LogEntry) GetWafBlockReason() string {
	if x != nil {
		return x.WafBlockReason
	}
	return ""
}

func (x *LogEntry) GetWafScore() int32 {
	if x != nil {
		return x.WafScore
	}
	return 0
}

func (x *LogEntry) GetWafAction() string {
	if x != nil {
		return x.WafAction
	}
	return ""
}

func (x *LogEntry) GetUserIdentity() *UserIdentity {
	if x != nil {
		return x.UserIdentity
	}
	return nil
}

func (x *LogEntry) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *LogEntry) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type UserIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        map[string]string      `protobuf:"bytes,1,rep,name=claims,proto3" json:"claims,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Verified      bool                   `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // "jwt_verify" or "jwt_decode"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdentity) Reset() {
	*x = UserIdentity{}
	mi := &file_proto_logpb_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdentity) ProtoMessage() {}

func (x *UserIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdentity.ProtoReflect.Descriptor instead.
func (*UserIdentity) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{1}
}

func (x *UserIdentity) GetClaims() map[string]string {
	if x != nil {
		return x.Claims
	}
	return nil
}

func (x *UserIdentity) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *UserIdentity) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_proto_logpb_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{2}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_logpb_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{3}
}

type SearchLogsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Host        string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Path        string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method      string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ClientIp    string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	StatusMin   int32                  `protobuf:"varint,5,opt,name=status_min,json=statusMin,proto3" json:"status_min,omitempty"`
	StatusMax   int32                  `protobuf:"varint,6,opt,name=status_max,json=statusMax,proto3" json:"status_max,omitempty"`
	From        string                 `protobuf:"bytes,7,opt,name=from,proto3" json:"from,omitempty"` // RFC3339
	To          string                 `protobuf:"bytes,8,opt,name=to,proto3" json:"to,omitempty"`
	Search      string                 `protobuf:"bytes,9,opt,name=search,proto3" json:"search,omitempty"` // full text on bodies
	Starred     bool                   `protobuf:"varint,10,opt,name=starred,proto3" json:"starred,omitempty"`
	RespTimeMin int32                  `protobuf:"varint,11,opt,name=resp_time_min,json=respTimeMin,proto3" json:"resp_time_min,omitempty"`
	RespTimeMax int32                  `protobuf:"varint,12,opt,name=resp_time_max,json=respTimeMax,proto3" json:"resp_time_max,omitempty"`
	Limit       int32                  `protobuf:"varint,13,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset      int32                  `protobuf:"varint,14,opt,name=offset,proto3" json:"offset,omitempty"`
	// Match against JWT claims (email, sub, name). Backend ORs all three.
	User          string `protobuf:"bytes,15,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsRequest) Reset() {
	*x = SearchLogsRequest{}
	mi := &file_proto_logpb_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsRequest) ProtoMessage() {}

func (x *SearchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{4}
}

func (x *SearchLogsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SearchLogsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SearchLogsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SearchLogsRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *SearchLogsRequest) GetStatusMin() int32 {
	if x != nil {
		return x.StatusMin
	}
	return 0
}

func (x *SearchLogsRequest) GetStatusMax() int32 {
	if x != nil {
		return x.StatusMax
	}
	return 0
}

func (x *SearchLogsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SearchLogsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SearchLogsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SearchLogsRequest) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *SearchLogsRequest) GetRespTimeMin() int32 {
	if x != nil {
		return x.RespTimeMin
	}
	return 0
}

func (x *SearchLogsRequest) GetRespTimeMax() int32 {
	if x != nil {
		return x.RespTimeMax
	}
	return 0
}

func (x *SearchLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchLogsRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

type SearchLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogSummary          `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsResponse) Reset() {
	*x = SearchLogsResponse{}
	mi := &file_proto_logpb_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsResponse) ProtoMessage() {}

func (x *SearchLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsResponse.ProtoReflect.Descriptor instead.
func (*SearchLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{5}
}

func (x *SearchLogsResponse) GetLogs() []*LogSummary {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *SearchLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type LogSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp      string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Host           string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	ClientIp       string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Method         string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Path           string                 `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	ResponseStatus int32                  `protobuf:"varint,7,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseTimeMs int32                  `protobuf:"varint,8,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	UserAgent      string                 `protobuf:"bytes,9,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	WafBlocked     bool                   `protobuf:"varint,10,opt,name=waf_blocked,json=wafBlocked,proto3" json:"waf_blocked,omitempty"`
	WafAction      string                 `protobuf:"bytes,11,opt,name=waf_action,json=wafAction,proto3" json:"waf_action,omitempty"`
	Starred        bool                   `protobuf:"varint,12,opt,name=starred,proto3" json:"starred,omitempty"`
	Country        string                 `protobuf:"bytes,13,opt,name=country,proto3" json:"country,omitempty"`
	City           string                 `protobuf:"bytes,14,opt,name=city,proto3" json:"city,omitempty"`
	// Summary identity — full UserIdentity is available in LogDetail; here
	// we send only the display claim so the list view can show "alice@foo.com"
	// without shipping every claim for every row.
	UserDisplay string `protobuf:"bytes,15,opt,name=user_display,json=userDisplay,proto3" json:"user_display,omitempty"`
	// Query value that matches the row in SearchLogs({ user }).
	UserQuery     string `protobuf:"bytes,16,opt,name=user_query,json=userQuery,proto3" json:"user_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSummary) Reset() {
	*x = LogSummary{}
	mi := &file_proto_logpb_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSummary) ProtoMessage() {}

func (x *LogSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSummary.ProtoReflect.Descriptor instead.
func (*LogSummary) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{6}
}

func (x *LogSummary) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *LogSummary) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogSummary) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LogSummary) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LogSummary) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LogSummary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LogSummary) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *LogSummary) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *LogSummary) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LogSummary) GetWafBlocked() bool {
	if x != nil {
		return x.WafBlocked
	}
	return false
}

func (x *LogSummary) GetWafAction() string {
	if x != nil {
		return x.WafAction
	}
	return ""
}

func (x *LogSummary) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *LogSummary) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *LogSummary) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *LogSummary) GetUserDisplay() string {
	if x != nil {
		return x.UserDisplay
	}
	return ""
}

func (x *LogSummary) GetUserQuery() string {
	if x != nil {
		return x.UserQuery
	}
	return ""
}

type GetLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogRequest) Reset() {
	*x = GetLogRequest{}
	mi := &file_proto_logpb_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogRequest) ProtoMessage() {}

func (x *GetLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogRequest.ProtoReflect.Descriptor instead.
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{7}
}

func (x *GetLogRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type LogDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LogEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	Starred       bool                   `protobuf:"varint,3,opt,name=starred,proto3" json:"starred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogDetail) Reset() {
	*x = LogDetail{}
	mi := &file_proto_logpb_log_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogDetail) ProtoMessage() {}

func (x *LogDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogDetail.ProtoReflect.Descriptor instead.
func (*LogDetail) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{8}
}

func (x *LogDetail) GetEntry() *LogEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *LogDetail) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *LogDetail) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

type GetLogStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLogStatsRequest) Reset() {
	*x = GetLogStatsRequest{}
	mi := &file_proto_logpb_log_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLogStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLogStatsRequest) ProtoMessage() {}

func (x *GetLogStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLogStatsRequest.ProtoReflect.Descriptor instead.
func (*GetLogStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{9}
}

func (x *GetLogStatsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetLogStatsRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetLogStatsRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type LogStatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalRequests      int64                  `protobuf:"varint,1,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalErrors        int64                  `protobuf:"varint,2,opt,name=total_errors,json=totalErrors,proto3" json:"total_errors,omitempty"` // 4xx + 5xx
	AvgResponseMs      float64                `protobuf:"fixed64,3,opt,name=avg_response_ms,json=avgResponseMs,proto3" json:"avg_response_ms,omitempty"`
	P95ResponseMs      float64                `protobuf:"fixed64,4,opt,name=p95_response_ms,json=p95ResponseMs,proto3" json:"p95_response_ms,omitempty"`
	P99ResponseMs      float64                `protobuf:"fixed64,5,opt,name=p99_response_ms,json=p99ResponseMs,proto3" json:"p99_response_ms,omitempty"`
	StatusDistribution map[string]int64       `protobuf:"bytes,6,rep,name=status_distribution,json=statusDistribution,proto3" json:"status_distribution,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Pre-rendered JSON strings for the dashboard panels. Plain JSON avoids
	// a per-field schema evolution on the rpc every time a new breakdown
	// gets added.
	TopCountriesJson string  `protobuf:"bytes,7,opt,name=top_countries_json,json=topCountriesJson,proto3" json:"top_countries_json,omitempty"`
	TopHostsJson     string  `protobuf:"bytes,8,opt,name=top_hosts_json,json=topHostsJson,proto3" json:"top_hosts_json,omitempty"`
	TopPathsJson     string  `protobuf:"bytes,9,opt,name=top_paths_json,json=topPathsJson,proto3" json:"top_paths_json,omitempty"`
	TopUsersJson     string  `protobuf:"bytes,10,opt,name=top_users_json,json=topUsersJson,proto3" json:"top_users_json,omitempty"`
	RequestsPerMin   float64 `protobuf:"fixed64,11,opt,name=requests_per_min,json=requestsPerMin,proto3" json:"requests_per_min,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogStatsResponse) Reset() {
	*x = LogStatsResponse{}
	mi := &file_proto_logpb_log_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogStatsResponse) ProtoMessage() {}

func (x *LogStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogStatsResponse.ProtoReflect.Descriptor instead.
func (*LogStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{10}
}

func (x *LogStatsResponse) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *LogStatsResponse) GetTotalErrors() int64 {
	if x != nil {
		return x.TotalErrors
	}
	return 0
}

func (x *LogStatsResponse) GetAvgResponseMs() float64 {
	if x != nil {
		return x.AvgResponseMs
	}
	return 0
}

func (x *LogStatsResponse) GetP95ResponseMs() float64 {
	if x != nil {
		return x.P95ResponseMs
	}
	return 0
}

func (x *LogStatsResponse) GetP99ResponseMs() float64 {
	if x != nil {
		return x.P99ResponseMs
	}
	return 0
}

func (x *LogStatsResponse) GetStatusDistribution() map[string]int64 {
	if x != nil {
		return x.StatusDistribution
	}
	return nil
}

func (x *LogStatsResponse) GetTopCountriesJson() string {
	if x != nil {
		return x.TopCountriesJson
	}
	return ""
}

func (x *LogStatsResponse) GetTopHostsJson() string {
	if x != nil {
		return x.TopHostsJson
	}
	return ""
}

func (x *LogStatsResponse) GetTopPathsJson() string {
	if x != nil {
		return x.TopPathsJson
	}
	return ""
}

func (x *LogStatsResponse) GetTopUsersJson() string {
	if x != nil {
		return x.TopUsersJson
	}
	return ""
}

func (x *LogStatsResponse) GetRequestsPerMin() float64 {
	if x != nil {
		return x.RequestsPerMin
	}
	return 0
}

type StreamLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"` // filter by host, empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsRequest) Reset() {
	*x = StreamLogsRequest{}
	mi := &file_proto_logpb_log_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsRequest) ProtoMessage() {}

func (x *StreamLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{11}
}

func (x *StreamLogsRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type UpsertNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertNoteRequest) Reset() {
	*x = UpsertNoteRequest{}
	mi := &file_proto_logpb_log_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertNoteRequest) ProtoMessage() {}

func (x *UpsertNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertNoteRequest.ProtoReflect.Descriptor instead.
func (*UpsertNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertNoteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpsertNoteRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type ToggleStarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleStarRequest) Reset() {
	*x = ToggleStarRequest{}
	mi := &file_proto_logpb_log_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleStarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleStarRequest) ProtoMessage() {}

func (x *ToggleStarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logpb_log_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleStarRequest.ProtoReflect.Descriptor instead.
func (*ToggleStarRequest) Descriptor() ([]byte, []int) {
	return file_proto_logpb_log_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleStarRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_proto_logpb_log_proto protoreflect.FileDescriptor

const file_proto_logpb_log_proto_rawDesc = "" +
	"\n" +
	"\x15proto/logpb/log.proto\x12\x05logpb\"\xda\b\n" +
	"\bLogEntry\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12!\n" +
	"\fquery_string\x18\a \x01(\tR\vqueryString\x12L\n" +
	"\x0frequest_headers\x18\b \x03(\v2#.logpb.LogEntry.RequestHeadersEntryR\x0erequestHeaders\x12'\n" +
	"\x0fresponse_status\x18\t \x01(\x05R\x0eresponseStatus\x12O\n" +
	"\x10response_headers\x18\n" +
	" \x03(\v2$.logpb.LogEntry.ResponseHeadersEntryR\x0fresponseHeaders\x12(\n" +
	"\x10response_time_ms\x18\v \x01(\x05R\x0eresponseTimeMs\x12!\n" +
	"\frequest_size\x18\f \x01(\x05R\vrequestSize\x12#\n" +
	"\rresponse_size\x18\r \x01(\x05R\fresponseSize\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x0e \x01(\tR\tuserAgent\x12\x14\n" +
	"\x05error\x18\x0f \x01(\tR\x05error\x12!\n" +
	"\frequest_body\x18\x10 \x01(\fR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\x11 \x01(\fR\fresponseBody\x120\n" +
	"\x14is_request_truncated\x18\x12 \x01(\bR\x12isRequestTruncated\x122\n" +
	"\x15is_response_truncated\x18\x13 \x01(\bR\x13isResponseTruncated\x12\x1f\n" +
	"\vwaf_blocked\x18\x14 \x01(\bR\n" +
	"wafBlocked\x12(\n" +
	"\x10waf_block_reason\x18\x15 \x01(\tR\x0ewafBlockReason\x12\x1b\n" +
	"\twaf_score\x18\x16 \x01(\x05R\bwafScore\x12\x1d\n" +
	"\n" +
	"waf_action\x18\x17 \x01(\tR\twafAction\x128\n" +
	"\ruser_identity\x18\x18 \x01(\v2\x13.logpb.UserIdentityR\fuserIdentity\x12\x18\n" +
	"\acountry\x18\x19 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x1a \x01(\tR\x04city\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x01\n" +
	"\fUserIdentity\x127\n" +
	"\x06claims\x18\x01 \x03(\v2\x1f.logpb.UserIdentity.ClaimsEntryR\x06claims\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x1a9\n" +
	"\vClaimsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\bLogBatch\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.logpb.LogEntryR\aentries\"\x05\n" +
	"\x03Ack\"\x8e\x03\n" +
	"\x11SearchLogsRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"status_min\x18\x05 \x01(\x05R\tstatusMin\x12\x1d\n" +
	"\n" +
	"status_max\x18\x06 \x01(\x05R\tstatusMax\x12\x12\n" +
	"\x04from\x18\a \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\b \x01(\tR\x02to\x12\x16\n" +
	"\x06search\x18\t \x01(\tR\x06search\x12\x18\n" +
	"\astarred\x18\n" +
	" \x01(\bR\astarred\x12\"\n" +
	"\rresp_time_min\x18\v \x01(\x05R\vrespTimeMin\x12\"\n" +
	"\rresp_time_max\x18\f \x01(\x05R\vrespTimeMax\x12\x14\n" +
	"\x05limit\x18\r \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x0e \x01(\x05R\x06offset\x12\x12\n" +
	"\x04user\x18\x0f \x01(\tR\x04user\"Q\n" +
	"\x12SearchLogsResponse\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.logpb.LogSummaryR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe2\x03\n" +
	"\n" +
	"LogSummary\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x06 \x01(\tR\x04path\x12'\n" +
	"\x0fresponse_status\x18\a \x01(\x05R\x0eresponseStatus\x12(\n" +
	"\x10response_time_ms\x18\b \x01(\x05R\x0eresponseTimeMs\x12\x1d\n" +
	"\n" +
	"user_agent\x18\t \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vwaf_blocked\x18\n" +
	" \x01(\bR\n" +
	"wafBlocked\x12\x1d\n" +
	"\n" +
	"waf_action\x18\v \x01(\tR\twafAction\x12\x18\n" +
	"\astarred\x18\f \x01(\bR\astarred\x12\x18\n" +
	"\acountry\x18\r \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x0e \x01(\tR\x04city\x12!\n" +
	"\fuser_display\x18\x0f \x01(\tR\vuserDisplay\x12\x1d\n" +
	"\n" +
	"user_query\x18\x10 \x01(\tR\tuserQuery\".\n" +
	"\rGetLogRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"`\n" +
	"\tLogDetail\x12%\n" +
	"\x05entry\x18\x01 \x01(\v2\x0f.logpb.LogEntryR\x05entry\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\x12\x18\n" +
	"\astarred\x18\x03 \x01(\bR\astarred\"L\n" +
	"\x12GetLogStatsRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"\xc7\x04\n" +
	"\x10LogStatsResponse\x12%\n" +
	"\x0etotal_requests\x18\x01 \x01(\x03R\rtotalRequests\x12!\n" +
	"\ftotal_errors\x18\x02 \x01(\x03R\vtotalErrors\x12&\n" +
	"\x0favg_response_ms\x18\x03 \x01(\x01R\ravgResponseMs\x12&\n" +
	"\x0fp95_response_ms\x18\x04 \x01(\x01R\rp95ResponseMs\x12&\n" +
	"\x0fp99_response_ms\x18\x05 \x01(\x01R\rp99ResponseMs\x12`\n" +
	"\x13status_distribution\x18\x06 \x03(\v2/.logpb.LogStatsResponse.StatusDistributionEntryR\x12statusDistribution\x12,\n" +
	"\x12top_countries_json\x18\a \x01(\tR\x10topCountriesJson\x12$\n" +
	"\x0etop_hosts_json\x18\b \x01(\tR\ftopHostsJson\x12$\n" +
	"\x0etop_paths_json\x18\t \x01(\tR\ftopPathsJson\x12$\n" +
	"\x0etop_users_json\x18\n" +
	" \x01(\tR\ftopUsersJson\x12(\n" +
	"\x10requests_per_min\x18\v \x01(\x01R\x0erequestsPerMin\x1aE\n" +
	"\x17StatusDistributionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"'\n" +
	"\x11StreamLogsRequest\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\"F\n" +
	"\x11UpsertNoteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"2\n" +
	"\x11ToggleStarRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId2\xbb\x03\n" +
	"\n" +
	"LogService\x12(\n" +
	"\tSendEntry\x12\x0f.logpb.LogEntry\x1a\n" +
	".logpb.Ack\x12(\n" +
	"\tSendBatch\x12\x0f.logpb.LogBatch\x1a\n" +
	".logpb.Ack\x12A\n" +
	"\n" +
	"SearchLogs\x12\x18.logpb.SearchLogsRequest\x1a\x19.logpb.SearchLogsResponse\x120\n" +
	"\x06GetLog\x12\x14.logpb.GetLogRequest\x1a\x10.logpb.LogDetail\x12A\n" +
	"\vGetLogStats\x12\x19.logpb.GetLogStatsRequest\x1a\x17.logpb.LogStatsResponse\x129\n" +
	"\n" +
	"StreamLogs\x12\x18.logpb.StreamLogsRequest\x1a\x0f.logpb.LogEntry0\x01\x122\n" +
	"\n" +
	"UpsertNote\x12\x18.logpb.UpsertNoteRequest\x1a\n" +
	".logpb.Ack\x122\n" +
	"\n" +
	"ToggleStar\x12\x18.logpb.ToggleStarRequest\x1a\n" +
	".logpb.AckB\x14Z\x12dialog/proto/logpbb\x06proto3"

var (
	file_proto_logpb_log_proto_rawDescOnce sync.Once
	file_proto_logpb_log_proto_rawDescData []byte
)

func file_proto_logpb_log_proto_rawDescGZIP() []byte {
	file_proto_logpb_log_proto_rawDescOnce.Do(func() {
		file_proto_logpb_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logpb_log_proto_rawDesc), len(file_proto_logpb_log_proto_rawDesc)))
	})
	return file_proto_logpb_log_proto_rawDescData
}

var file_proto_logpb_log_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_logpb_log_proto_goTypes = []any{
	(*LogEntry)(nil),           // 0: logpb.LogEntry
	(*UserIdentity)(nil),       // 1: logpb.UserIdentity
	(*LogBatch)(nil),           // 2: logpb.LogBatch
	(*Ack)(nil),                // 3: logpb.Ack
	(*SearchLogsRequest)(nil),  // 4: logpb.SearchLogsRequest
	(*SearchLogsResponse)(nil), // 5: logpb.SearchLogsResponse
	(*LogSummary)(nil),         // 6: logpb.LogSummary
	(*GetLogRequest)(nil),      // 7: logpb.GetLogRequest
	(*LogDetail)(nil),          // 8: logpb.LogDetail
	(*GetLogStatsRequest)(nil), // 9: logpb.GetLogStatsRequest
	(*LogStatsResponse)(nil),   // 10: logpb.LogStatsResponse
	(*StreamLogsRequest)(nil),  // 11: logpb.StreamLogsRequest
	(*UpsertNoteRequest)(nil),  // 12: logpb.UpsertNoteRequest
	(*ToggleStarRequest)(nil),  // 13: logpb.ToggleStarRequest
	nil,                        // 14: logpb.LogEntry.RequestHeadersEntry
	nil,                        // 15: logpb.LogEntry.ResponseHeadersEntry
	nil,                        // 16: logpb.UserIdentity.ClaimsEntry
	nil,                        // 17: logpb.LogStatsResponse.StatusDistributionEntry
}
var file_proto_logpb_log_proto_depIdxs = []int32{
	14, // 0: logpb.LogEntry.request_headers:type_name -> logpb.LogEntry.RequestHeadersEntry
	15, // 1: logpb.LogEntry.response_headers:type_name -> logpb.LogEntry.ResponseHeadersEntry
	1,  // 2: logpb.LogEntry.user_identity:type_name -> logpb.UserIdentity
	16, // 3: logpb.UserIdentity.claims:type_name -> logpb.UserIdentity.ClaimsEntry
	0,  // 4: logpb.LogBatch.entries:type_name -> logpb.LogEntry
	6,  // 5: logpb.SearchLogsResponse.logs:type_name -> logpb.LogSummary
	0,  // 6: logpb.LogDetail.entry:type_name -> logpb.LogEntry
	17, // 7: logpb.LogStatsResponse.status_distribution:type_name -> logpb.LogStatsResponse.StatusDistributionEntry
	0,  // 8: logpb.LogService.SendEntry:input_type -> logpb.LogEntry
	2,  // 9: logpb.LogService.SendBatch:input_type -> logpb.LogBatch
	4,  // 10: logpb.LogService.SearchLogs:input_type -> logpb.SearchLogsRequest
	7,  // 11: logpb.LogService.GetLog:input_type -> logpb.GetLogRequest
	9,  // 12: logpb.LogService.GetLogStats:input_type -> logpb.GetLogStatsRequest
	11, // 13: logpb.LogService.StreamLogs:input_type -> logpb.StreamLogsRequest
	12, // 14: logpb.LogService.UpsertNote:input_type -> logpb.UpsertNoteRequest
	13, // 15: logpb.LogService.ToggleStar:input_type -> logpb.ToggleStarRequest
	3,  // 16: logpb.LogService.SendEntry:output_type -> logpb.Ack
	3,  // 17: logpb.LogService.SendBatch:output_type -> logpb.Ack
	5,  // 18: logpb.LogService.SearchLogs:output_type -> logpb.SearchLogsResponse
	8,  // 19: logpb.LogService.GetLog:output_type -> logpb.LogDetail
	10, // 20: logpb.LogService.GetLogStats:output_type -> logpb.LogStatsResponse
	0,  // 21: logpb.LogService.StreamLogs:output_type -> logpb.LogEntry
	3,  // 22: logpb.LogService.UpsertNote:output_type -> logpb.Ack
	3,  // 23: logpb.LogService.ToggleStar:output_type -> logpb.Ack
	16, // [16:24] is the sub-list for method output_type
	8,  // [8:16] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_logpb_log_proto_init() }
func file_proto_logpb_log_proto_init() {
	if File_proto_logpb_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logpb_log_proto_rawDesc), len(file_proto_logpb_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logpb_log_proto_goTypes,
		DependencyIndexes: file_proto_logpb_log_proto_depIdxs,
		MessageInfos:      file_proto_logpb_log_proto_msgTypes,
	}.Build()
	File_proto_logpb_log_proto = out.File
	file_proto_logpb_log_proto_goTypes = nil
	file_proto_logpb_log_proto_depIdxs = nil
}
