// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/logpb/log.proto

package logpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogService_SendEntry_FullMethodName              = "/logpb.LogService/SendEntry"
	LogService_SendBatch_FullMethodName              = "/logpb.LogService/SendBatch"
	LogService_SearchLogs_FullMethodName             = "/logpb.LogService/SearchLogs"
	LogService_GetLog_FullMethodName                 = "/logpb.LogService/GetLog"
	LogService_GetLogStats_FullMethodName            = "/logpb.LogService/GetLogStats"
	LogService_StreamLogs_FullMethodName             = "/logpb.LogService/StreamLogs"
	LogService_UpsertNote_FullMethodName             = "/logpb.LogService/UpsertNote"
	LogService_ToggleStar_FullMethodName             = "/logpb.LogService/ToggleStar"
	LogService_GetEnrichmentStatus_FullMethodName    = "/logpb.LogService/GetEnrichmentStatus"
	LogService_GetLogRawJWT_FullMethodName           = "/logpb.LogService/GetLogRawJWT"
	LogService_SendContainerLogBatch_FullMethodName  = "/logpb.LogService/SendContainerLogBatch"
	LogService_SearchContainerLogs_FullMethodName    = "/logpb.LogService/SearchContainerLogs"
	LogService_ListContainers_FullMethodName         = "/logpb.LogService/ListContainers"
	LogService_GetContainerLogContext_FullMethodName = "/logpb.LogService/GetContainerLogContext"
	LogService_GetIngestStatus_FullMethodName        = "/logpb.LogService/GetIngestStatus"
	LogService_GetContainerLastLogAt_FullMethodName  = "/logpb.LogService/GetContainerLastLogAt"
)

// LogServiceClient is the client API for LogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LogService — diaLOG SIEM'in gRPC API'si.
// MUVON proxy log entry'lerini bu servise gonderir.
type LogServiceClient interface {
	// SendEntry: tek bir log entry gonder (fire-and-forget).
	SendEntry(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*Ack, error)
	// SendBatch: toplu log entry gonder (yuksek throughput).
	SendBatch(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*Ack, error)
	// --- Arama / Okuma (admin frontend tarafindan kullanilir) ---
	SearchLogs(ctx context.Context, in *SearchLogsRequest, opts ...grpc.CallOption) (*SearchLogsResponse, error)
	GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*LogDetail, error)
	GetLogStats(ctx context.Context, in *GetLogStatsRequest, opts ...grpc.CallOption) (*LogStatsResponse, error)
	// --- SSE yerine gRPC stream ---
	StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// --- Not / Star ---
	UpsertNote(ctx context.Context, in *UpsertNoteRequest, opts ...grpc.CallOption) (*Ack, error)
	ToggleStar(ctx context.Context, in *ToggleStarRequest, opts ...grpc.CallOption) (*Ack, error)
	// --- Enrichment health ---
	// Reports whether GeoIP and JWT identity enrichment are actually wired up
	// and operating. The admin panel uses this to show an actionable banner
	// when a setting is enabled but the underlying loader has failed (e.g. a
	// mistyped path, a missing file). Without this signal the symptom is just
	// empty country / user fields with no visible cause.
	GetEnrichmentStatus(ctx context.Context, in *EnrichmentStatusRequest, opts ...grpc.CallOption) (*EnrichmentStatusResponse, error)
	// --- Reveal raw JWT ---
	// Fetches the raw bearer token captured on a single log row. Available
	// only when the host opted into hosts.store_raw_jwt. Callers (admin) are
	// expected to wrap this in an audit log entry — the SIEM does not record
	// who pulled the token.
	GetLogRawJWT(ctx context.Context, in *GetLogRawJWTRequest, opts ...grpc.CallOption) (*GetLogRawJWTResponse, error)
	// --- Container Logs (stdout/stderr from managed containers) ---
	// SendContainerLogBatch ingests a batch of container log lines emitted by
	// muvon-deployer (central host) or the agent's dockerwatch (remote hosts).
	// Fire-and-forget — caller does not wait for write to PostgreSQL.
	SendContainerLogBatch(ctx context.Context, in *ContainerLogBatch, opts ...grpc.CallOption) (*Ack, error)
	// SearchContainerLogs queries persisted container logs with filters and
	// cursor-based pagination on UUIDv7 ids. Supports free-text ILIKE and
	// structured attrs (jsonb_path_ops) lookup.
	SearchContainerLogs(ctx context.Context, in *SearchContainerLogsRequest, opts ...grpc.CallOption) (*SearchContainerLogsResponse, error)
	// ListContainers returns dimension-table rows (one per container ever
	// seen). Survives container deletion — used by the UI picker so silently
	// dead containers (the user's incident scenario) remain selectable.
	ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error)
	// GetContainerLogContext returns N lines around a given log id (same
	// container_id). Lets the UI's "View context" surface ±50 lines.
	GetContainerLogContext(ctx context.Context, in *GetContainerLogContextRequest, opts ...grpc.CallOption) (*SearchContainerLogsResponse, error)
	// GetIngestStatus reports container-log shipper health (spool size, lag,
	// last batch received). The admin UI surfaces this as an "ingestion
	// degraded" banner so operators can act before the spool overflows.
	GetIngestStatus(ctx context.Context, in *IngestStatusRequest, opts ...grpc.CallOption) (*IngestStatusResponse, error)
	// GetContainerLastLogAt returns the timestamp of the latest container_log
	// row for the given container, used by logship to resume tailing with
	// `since=<last_log_at>` after a deployer restart. Without this, every
	// restart re-ingests the last `tail=10000` lines and creates duplicate
	// hypertable rows.
	GetContainerLastLogAt(ctx context.Context, in *GetContainerLastLogAtRequest, opts ...grpc.CallOption) (*GetContainerLastLogAtResponse, error)
}

type logServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServiceClient(cc grpc.ClientConnInterface) LogServiceClient {
	return &logServiceClient{cc}
}

func (c *logServiceClient) SendEntry(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, LogService_SendEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SendBatch(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, LogService_SendBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SearchLogs(ctx context.Context, in *SearchLogsRequest, opts ...grpc.CallOption) (*SearchLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchLogsResponse)
	err := c.cc.Invoke(ctx, LogService_SearchLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*LogDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogDetail)
	err := c.cc.Invoke(ctx, LogService_GetLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetLogStats(ctx context.Context, in *GetLogStatsRequest, opts ...grpc.CallOption) (*LogStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogStatsResponse)
	err := c.cc.Invoke(ctx, LogService_GetLogStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) StreamLogs(ctx context.Context, in *StreamLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogService_ServiceDesc.Streams[0], LogService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamLogsRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *logServiceClient) UpsertNote(ctx context.Context, in *UpsertNoteRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, LogService_UpsertNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) ToggleStar(ctx context.Context, in *ToggleStarRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, LogService_ToggleStar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetEnrichmentStatus(ctx context.Context, in *EnrichmentStatusRequest, opts ...grpc.CallOption) (*EnrichmentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichmentStatusResponse)
	err := c.cc.Invoke(ctx, LogService_GetEnrichmentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetLogRawJWT(ctx context.Context, in *GetLogRawJWTRequest, opts ...grpc.CallOption) (*GetLogRawJWTResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLogRawJWTResponse)
	err := c.cc.Invoke(ctx, LogService_GetLogRawJWT_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SendContainerLogBatch(ctx context.Context, in *ContainerLogBatch, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, LogService_SendContainerLogBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) SearchContainerLogs(ctx context.Context, in *SearchContainerLogsRequest, opts ...grpc.CallOption) (*SearchContainerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchContainerLogsResponse)
	err := c.cc.Invoke(ctx, LogService_SearchContainerLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) ListContainers(ctx context.Context, in *ListContainersRequest, opts ...grpc.CallOption) (*ListContainersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListContainersResponse)
	err := c.cc.Invoke(ctx, LogService_ListContainers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetContainerLogContext(ctx context.Context, in *GetContainerLogContextRequest, opts ...grpc.CallOption) (*SearchContainerLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchContainerLogsResponse)
	err := c.cc.Invoke(ctx, LogService_GetContainerLogContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetIngestStatus(ctx context.Context, in *IngestStatusRequest, opts ...grpc.CallOption) (*IngestStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestStatusResponse)
	err := c.cc.Invoke(ctx, LogService_GetIngestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logServiceClient) GetContainerLastLogAt(ctx context.Context, in *GetContainerLastLogAtRequest, opts ...grpc.CallOption) (*GetContainerLastLogAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContainerLastLogAtResponse)
	err := c.cc.Invoke(ctx, LogService_GetContainerLastLogAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServiceServer is the server API for LogService service.
// All implementations must embed UnimplementedLogServiceServer
// for forward compatibility.
//
// LogService — diaLOG SIEM'in gRPC API'si.
// MUVON proxy log entry'lerini bu servise gonderir.
type LogServiceServer interface {
	// SendEntry: tek bir log entry gonder (fire-and-forget).
	SendEntry(context.Context, *LogEntry) (*Ack, error)
	// SendBatch: toplu log entry gonder (yuksek throughput).
	SendBatch(context.Context, *LogBatch) (*Ack, error)
	// --- Arama / Okuma (admin frontend tarafindan kullanilir) ---
	SearchLogs(context.Context, *SearchLogsRequest) (*SearchLogsResponse, error)
	GetLog(context.Context, *GetLogRequest) (*LogDetail, error)
	GetLogStats(context.Context, *GetLogStatsRequest) (*LogStatsResponse, error)
	// --- SSE yerine gRPC stream ---
	StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error
	// --- Not / Star ---
	UpsertNote(context.Context, *UpsertNoteRequest) (*Ack, error)
	ToggleStar(context.Context, *ToggleStarRequest) (*Ack, error)
	// --- Enrichment health ---
	// Reports whether GeoIP and JWT identity enrichment are actually wired up
	// and operating. The admin panel uses this to show an actionable banner
	// when a setting is enabled but the underlying loader has failed (e.g. a
	// mistyped path, a missing file). Without this signal the symptom is just
	// empty country / user fields with no visible cause.
	GetEnrichmentStatus(context.Context, *EnrichmentStatusRequest) (*EnrichmentStatusResponse, error)
	// --- Reveal raw JWT ---
	// Fetches the raw bearer token captured on a single log row. Available
	// only when the host opted into hosts.store_raw_jwt. Callers (admin) are
	// expected to wrap this in an audit log entry — the SIEM does not record
	// who pulled the token.
	GetLogRawJWT(context.Context, *GetLogRawJWTRequest) (*GetLogRawJWTResponse, error)
	// --- Container Logs (stdout/stderr from managed containers) ---
	// SendContainerLogBatch ingests a batch of container log lines emitted by
	// muvon-deployer (central host) or the agent's dockerwatch (remote hosts).
	// Fire-and-forget — caller does not wait for write to PostgreSQL.
	SendContainerLogBatch(context.Context, *ContainerLogBatch) (*Ack, error)
	// SearchContainerLogs queries persisted container logs with filters and
	// cursor-based pagination on UUIDv7 ids. Supports free-text ILIKE and
	// structured attrs (jsonb_path_ops) lookup.
	SearchContainerLogs(context.Context, *SearchContainerLogsRequest) (*SearchContainerLogsResponse, error)
	// ListContainers returns dimension-table rows (one per container ever
	// seen). Survives container deletion — used by the UI picker so silently
	// dead containers (the user's incident scenario) remain selectable.
	ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error)
	// GetContainerLogContext returns N lines around a given log id (same
	// container_id). Lets the UI's "View context" surface ±50 lines.
	GetContainerLogContext(context.Context, *GetContainerLogContextRequest) (*SearchContainerLogsResponse, error)
	// GetIngestStatus reports container-log shipper health (spool size, lag,
	// last batch received). The admin UI surfaces this as an "ingestion
	// degraded" banner so operators can act before the spool overflows.
	GetIngestStatus(context.Context, *IngestStatusRequest) (*IngestStatusResponse, error)
	// GetContainerLastLogAt returns the timestamp of the latest container_log
	// row for the given container, used by logship to resume tailing with
	// `since=<last_log_at>` after a deployer restart. Without this, every
	// restart re-ingests the last `tail=10000` lines and creates duplicate
	// hypertable rows.
	GetContainerLastLogAt(context.Context, *GetContainerLastLogAtRequest) (*GetContainerLastLogAtResponse, error)
	mustEmbedUnimplementedLogServiceServer()
}

// UnimplementedLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServiceServer struct{}

func (UnimplementedLogServiceServer) SendEntry(context.Context, *LogEntry) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEntry not implemented")
}
func (UnimplementedLogServiceServer) SendBatch(context.Context, *LogBatch) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendBatch not implemented")
}
func (UnimplementedLogServiceServer) SearchLogs(context.Context, *SearchLogsRequest) (*SearchLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchLogs not implemented")
}
func (UnimplementedLogServiceServer) GetLog(context.Context, *GetLogRequest) (*LogDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLog not implemented")
}
func (UnimplementedLogServiceServer) GetLogStats(context.Context, *GetLogStatsRequest) (*LogStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogStats not implemented")
}
func (UnimplementedLogServiceServer) StreamLogs(*StreamLogsRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLogServiceServer) UpsertNote(context.Context, *UpsertNoteRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertNote not implemented")
}
func (UnimplementedLogServiceServer) ToggleStar(context.Context, *ToggleStarRequest) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleStar not implemented")
}
func (UnimplementedLogServiceServer) GetEnrichmentStatus(context.Context, *EnrichmentStatusRequest) (*EnrichmentStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnrichmentStatus not implemented")
}
func (UnimplementedLogServiceServer) GetLogRawJWT(context.Context, *GetLogRawJWTRequest) (*GetLogRawJWTResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogRawJWT not implemented")
}
func (UnimplementedLogServiceServer) SendContainerLogBatch(context.Context, *ContainerLogBatch) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SendContainerLogBatch not implemented")
}
func (UnimplementedLogServiceServer) SearchContainerLogs(context.Context, *SearchContainerLogsRequest) (*SearchContainerLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchContainerLogs not implemented")
}
func (UnimplementedLogServiceServer) ListContainers(context.Context, *ListContainersRequest) (*ListContainersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListContainers not implemented")
}
func (UnimplementedLogServiceServer) GetContainerLogContext(context.Context, *GetContainerLogContextRequest) (*SearchContainerLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainerLogContext not implemented")
}
func (UnimplementedLogServiceServer) GetIngestStatus(context.Context, *IngestStatusRequest) (*IngestStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIngestStatus not implemented")
}
func (UnimplementedLogServiceServer) GetContainerLastLogAt(context.Context, *GetContainerLastLogAtRequest) (*GetContainerLastLogAtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContainerLastLogAt not implemented")
}
func (UnimplementedLogServiceServer) mustEmbedUnimplementedLogServiceServer() {}
func (UnimplementedLogServiceServer) testEmbeddedByValue()                    {}

// UnsafeLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServiceServer will
// result in compilation errors.
type UnsafeLogServiceServer interface {
	mustEmbedUnimplementedLogServiceServer()
}

func RegisterLogServiceServer(s grpc.ServiceRegistrar, srv LogServiceServer) {
	// If the following call panics, it indicates UnimplementedLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogService_ServiceDesc, srv)
}

func _LogService_SendEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SendEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_SendEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SendEntry(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SendBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SendBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_SendBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SendBatch(ctx, req.(*LogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SearchLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SearchLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_SearchLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SearchLogs(ctx, req.(*SearchLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLog(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetLogStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLogStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetLogStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLogStats(ctx, req.(*GetLogStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogServiceServer).StreamLogs(m, &grpc.GenericServerStream[StreamLogsRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogService_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _LogService_UpsertNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).UpsertNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_UpsertNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).UpsertNote(ctx, req.(*UpsertNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_ToggleStar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleStarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ToggleStar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_ToggleStar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ToggleStar(ctx, req.(*ToggleStarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetEnrichmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetEnrichmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetEnrichmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetEnrichmentStatus(ctx, req.(*EnrichmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetLogRawJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRawJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetLogRawJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetLogRawJWT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetLogRawJWT(ctx, req.(*GetLogRawJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SendContainerLogBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerLogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SendContainerLogBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_SendContainerLogBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SendContainerLogBatch(ctx, req.(*ContainerLogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_SearchContainerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchContainerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).SearchContainerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_SearchContainerLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).SearchContainerLogs(ctx, req.(*SearchContainerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_ListContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).ListContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_ListContainers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).ListContainers(ctx, req.(*ListContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetContainerLogContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerLogContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetContainerLogContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetContainerLogContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetContainerLogContext(ctx, req.(*GetContainerLogContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetIngestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetIngestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetIngestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetIngestStatus(ctx, req.(*IngestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogService_GetContainerLastLogAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerLastLogAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServiceServer).GetContainerLastLogAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogService_GetContainerLastLogAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServiceServer).GetContainerLastLogAt(ctx, req.(*GetContainerLastLogAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogService_ServiceDesc is the grpc.ServiceDesc for LogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logpb.LogService",
	HandlerType: (*LogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEntry",
			Handler:    _LogService_SendEntry_Handler,
		},
		{
			MethodName: "SendBatch",
			Handler:    _LogService_SendBatch_Handler,
		},
		{
			MethodName: "SearchLogs",
			Handler:    _LogService_SearchLogs_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _LogService_GetLog_Handler,
		},
		{
			MethodName: "GetLogStats",
			Handler:    _LogService_GetLogStats_Handler,
		},
		{
			MethodName: "UpsertNote",
			Handler:    _LogService_UpsertNote_Handler,
		},
		{
			MethodName: "ToggleStar",
			Handler:    _LogService_ToggleStar_Handler,
		},
		{
			MethodName: "GetEnrichmentStatus",
			Handler:    _LogService_GetEnrichmentStatus_Handler,
		},
		{
			MethodName: "GetLogRawJWT",
			Handler:    _LogService_GetLogRawJWT_Handler,
		},
		{
			MethodName: "SendContainerLogBatch",
			Handler:    _LogService_SendContainerLogBatch_Handler,
		},
		{
			MethodName: "SearchContainerLogs",
			Handler:    _LogService_SearchContainerLogs_Handler,
		},
		{
			MethodName: "ListContainers",
			Handler:    _LogService_ListContainers_Handler,
		},
		{
			MethodName: "GetContainerLogContext",
			Handler:    _LogService_GetContainerLogContext_Handler,
		},
		{
			MethodName: "GetIngestStatus",
			Handler:    _LogService_GetIngestStatus_Handler,
		},
		{
			MethodName: "GetContainerLastLogAt",
			Handler:    _LogService_GetContainerLastLogAt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LogService_StreamLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/logpb/log.proto",
}
